/*
Code automatically generated by asn1scc tool
*/
package asn1src

import asn1scala._
import stainless.lang._
import stainless.annotation._
import stainless.collection._
import stainless.proof._
import StaticChecks._

sealed trait TPeriodicGenerationActionStatus:
    def i: Int
object TPeriodicGenerationActionStatus:
    case object Tenabled extends TPeriodicGenerationActionStatus:
        override def i: Int = 0
    case object Tdisabled extends TPeriodicGenerationActionStatus:
        override def i: Int = 1

// please use the following macros to avoid breaking code.
// type Tenabled = TPeriodicGenerationActionStatus.enabled
// type Tdisabled = TPeriodicGenerationActionStatus.disabled

@inline @cCode.inline val ERR_PERIODICGENERATIONACTIONSTATUS: Int = 107 /*enabled | disabled */

 

@inline @cCode.inline val ERR_ACN_ENCODE_PERIODICGENERATIONACTIONSTATUS: Int = 110 /*  */
@inline @cCode.inline val TPeriodicGenerationActionStatus_REQUIRED_BYTES_FOR_ACN_ENCODING = 1
@inline @cCode.inline val TPeriodicGenerationActionStatus_REQUIRED_BITS_FOR_ACN_ENCODING = 1

@inline @cCode.inline val ERR_ACN_DECODE_PERIODICGENERATIONACTIONSTATUS: Int = 111 /*  */


