/*
Code automatically generated by asn1scc tool
*/
package asn1src

import asn1scala._
import stainless.lang._
import stainless.annotation._
import stainless.collection._
import stainless.proof._
import StaticChecks._

/*-- THousekeepingParameterReportStructureIntervals --------------------------------------------*/

case class THousekeepingParameterReportStructureIntervals (
    housekeepingParameterReportStructure_ID: THousekeepingParameterReportStructure_ID, 
    collectionInterval: TPUSC_UINT32
) {

    def size(offset: Long): Long = {
        require((0L <= offset) && (offset <= 9223372036854775743L))
        val size_0 = 32L
        val size_1 = 32L
        size_0 + size_1
    }.ensuring { (res: Long) => 
        res == 64L
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaAnyOffset(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854775743L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775743L))
        val size_0_offset = 32L
        val size_0_otherOffset = 32L
        val size_1_offset = 32L
        val size_1_otherOffset = 32L
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextByte(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854775743L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775743L))
        require((offset % 8L) == (otherOffset % 8L))
        val size_0_offset = 32L
        val size_0_otherOffset = 32L
        val size_1_offset = 32L
        val size_1_otherOffset = 32L
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextWord(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854775743L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775743L))
        require((offset % 16L) == (otherOffset % 16L))
        val size_0_offset = 32L
        val size_0_otherOffset = 32L
        val size_1_offset = 32L
        val size_1_otherOffset = 32L
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextDWord(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854775743L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775743L))
        require((offset % 32L) == (otherOffset % 32L))
        val size_0_offset = 32L
        val size_0_otherOffset = 32L
        val size_1_offset = 32L
        val size_1_otherOffset = 32L
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }
}


@inline @cCode.inline val ERR_HOUSEKEEPINGPARAMETERREPORTSTRUCTUREINTERVALS: Int = 1042 /* */
@inline @cCode.inline val ERR_HOUSEKEEPINGPARAMETERREPORTSTRUCTUREINTERVALS_HOUSEKEEPINGPARAMETERREPORTSTRUCTURE_ID_2: Int = 1022 /* */
@inline @cCode.inline val ERR_HOUSEKEEPINGPARAMETERREPORTSTRUCTUREINTERVALS_COLLECTIONINTERVAL_2_2: Int = 1037 /* */

 

@inline @cCode.inline val ERR_ACN_ENCODE_HOUSEKEEPINGPARAMETERREPORTSTRUCTUREINTERVALS: Int = 1045 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_HOUSEKEEPINGPARAMETERREPORTSTRUCTUREINTERVALS_HOUSEKEEPINGPARAMETERREPORTSTRUCTURE_ID_2: Int = 1025 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_HOUSEKEEPINGPARAMETERREPORTSTRUCTUREINTERVALS_COLLECTIONINTERVAL_2_2: Int = 1040 /*  */
@inline @cCode.inline val THousekeepingParameterReportStructureIntervals_REQUIRED_BYTES_FOR_ACN_ENCODING = 8
@inline @cCode.inline val THousekeepingParameterReportStructureIntervals_REQUIRED_BITS_FOR_ACN_ENCODING = 64

@inline @cCode.inline val ERR_ACN_DECODE_HOUSEKEEPINGPARAMETERREPORTSTRUCTUREINTERVALS: Int = 1046 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_HOUSEKEEPINGPARAMETERREPORTSTRUCTUREINTERVALS_HOUSEKEEPINGPARAMETERREPORTSTRUCTURE_ID_2: Int = 1026 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_HOUSEKEEPINGPARAMETERREPORTSTRUCTUREINTERVALS_COLLECTIONINTERVAL_2_2: Int = 1041 /*  */
/*-- TTC_3_31_ModifyTheCollectionIntervalOfHousekeepingParameterReportStructures --------------------------------------------*/


case class TTC_3_31_ModifyTheCollectionIntervalOfHousekeepingParameterReportStructures_housekeepingParamererReportStructureIntervals (nCount: Int, arr: Vector[THousekeepingParameterReportStructureIntervals])
{
    require(this.arr.size <= 63 && 1 <= this.nCount && this.nCount <= this.arr.size)

    def size(offset: Long): Long = {
        require((0L <= offset) && (offset <= 9223372036854771775L))
        TTC_3_31_ModifyTheCollectionIntervalOfHousekeepingParameterReportStructures_housekeepingParamererReportStructureIntervals.sizeRange(this.arr, offset, 0, this.nCount)
    }.ensuring { (res: Long) => 
        (0L <= res) && (res <= 4032L)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaAnyOffset(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854771775L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854771775L))
        TTC_3_31_ModifyTheCollectionIntervalOfHousekeepingParameterReportStructures_housekeepingParamererReportStructureIntervals.sizeLemmaAnyOffset(this.arr, offset, otherOffset, 0, this.nCount)
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextByte(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854771775L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854771775L))
        require((offset % 8L) == (otherOffset % 8L))
        TTC_3_31_ModifyTheCollectionIntervalOfHousekeepingParameterReportStructures_housekeepingParamererReportStructureIntervals.sizeLemmaNextByte(this.arr, offset, otherOffset, 0, this.nCount)
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextWord(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854771775L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854771775L))
        require((offset % 16L) == (otherOffset % 16L))
        TTC_3_31_ModifyTheCollectionIntervalOfHousekeepingParameterReportStructures_housekeepingParamererReportStructureIntervals.sizeLemmaNextWord(this.arr, offset, otherOffset, 0, this.nCount)
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextDWord(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854771775L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854771775L))
        require((offset % 32L) == (otherOffset % 32L))
        TTC_3_31_ModifyTheCollectionIntervalOfHousekeepingParameterReportStructures_housekeepingParamererReportStructureIntervals.sizeLemmaNextDWord(this.arr, offset, otherOffset, 0, this.nCount)
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }
}
object TTC_3_31_ModifyTheCollectionIntervalOfHousekeepingParameterReportStructures_housekeepingParamererReportStructureIntervals {
    def sizeRange(ls: Vector[THousekeepingParameterReportStructureIntervals], offset: Long, from: Int, to: Int): Long = {
        require((0 <= from) && (from <= to) && (to <= ls.size) && (ls.size <= 63))
        require((0L <= offset) && (offset <= 9223372036854775807L - 64L * (to - from)))
        decreases(to - from)
        if (from == to) {
            0L
        } else {
            val elemSize = ls.apply(from).size(offset)
            assert(elemSize == 64L)
            elemSize + TTC_3_31_ModifyTheCollectionIntervalOfHousekeepingParameterReportStructures_housekeepingParamererReportStructureIntervals.sizeRange(ls, offset + elemSize, from + 1, to)
        }
    }.ensuring { (res: Long) => 
        val nbElems = (to - from)
        (0L <= res && res <= 64L * nbElems)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaAnyOffset(ls: Vector[THousekeepingParameterReportStructureIntervals], offset: Long, otherOffset: Long, from: Int, to: Int): Unit = {
        require((0 <= from) && (from <= to) && (to <= ls.size) && (ls.size <= 63))
        require((0L <= offset) && (offset <= 9223372036854775807L - 64L * (to - from)))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775807L - 64L * (to - from)))
        decreases(to - from)
        if (from == to) {
            ()
        } else {
            val elemSizeOff = ls.apply(from).size(offset)
            val elemSizeOtherOff = ls.apply(from).size(otherOffset)
            assert(elemSizeOff == 64L)
            assert(elemSizeOtherOff == 64L)
            ls.apply(from).sizeLemmaAnyOffset(offset, otherOffset)
            TTC_3_31_ModifyTheCollectionIntervalOfHousekeepingParameterReportStructures_housekeepingParamererReportStructureIntervals.sizeLemmaAnyOffset(ls, offset + elemSizeOff, otherOffset + elemSizeOtherOff, from + 1, to)
        }
    }.ensuring { (_: Unit) => 
        TTC_3_31_ModifyTheCollectionIntervalOfHousekeepingParameterReportStructures_housekeepingParamererReportStructureIntervals.sizeRange(ls, offset, from, to) == TTC_3_31_ModifyTheCollectionIntervalOfHousekeepingParameterReportStructures_housekeepingParamererReportStructureIntervals.sizeRange(ls, otherOffset, from, to)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextByte(ls: Vector[THousekeepingParameterReportStructureIntervals], offset: Long, otherOffset: Long, from: Int, to: Int): Unit = {
        require((0 <= from) && (from <= to) && (to <= ls.size) && (ls.size <= 63))
        require((0L <= offset) && (offset <= 9223372036854775807L - 64L * (to - from)))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775807L - 64L * (to - from)))
        require((offset % 8L) == (otherOffset % 8L))
        decreases(to - from)
        if (from == to) {
            ()
        } else {
            val elemSizeOff = ls.apply(from).size(offset)
            val elemSizeOtherOff = ls.apply(from).size(otherOffset)
            assert(elemSizeOff == 64L)
            assert(elemSizeOtherOff == 64L)
            ls.apply(from).sizeLemmaNextByte(offset, otherOffset)
            TTC_3_31_ModifyTheCollectionIntervalOfHousekeepingParameterReportStructures_housekeepingParamererReportStructureIntervals.sizeLemmaNextByte(ls, offset + elemSizeOff, otherOffset + elemSizeOtherOff, from + 1, to)
        }
    }.ensuring { (_: Unit) => 
        TTC_3_31_ModifyTheCollectionIntervalOfHousekeepingParameterReportStructures_housekeepingParamererReportStructureIntervals.sizeRange(ls, offset, from, to) == TTC_3_31_ModifyTheCollectionIntervalOfHousekeepingParameterReportStructures_housekeepingParamererReportStructureIntervals.sizeRange(ls, otherOffset, from, to)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextWord(ls: Vector[THousekeepingParameterReportStructureIntervals], offset: Long, otherOffset: Long, from: Int, to: Int): Unit = {
        require((0 <= from) && (from <= to) && (to <= ls.size) && (ls.size <= 63))
        require((0L <= offset) && (offset <= 9223372036854775807L - 64L * (to - from)))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775807L - 64L * (to - from)))
        require((offset % 16L) == (otherOffset % 16L))
        decreases(to - from)
        if (from == to) {
            ()
        } else {
            val elemSizeOff = ls.apply(from).size(offset)
            val elemSizeOtherOff = ls.apply(from).size(otherOffset)
            assert(elemSizeOff == 64L)
            assert(elemSizeOtherOff == 64L)
            ls.apply(from).sizeLemmaNextWord(offset, otherOffset)
            TTC_3_31_ModifyTheCollectionIntervalOfHousekeepingParameterReportStructures_housekeepingParamererReportStructureIntervals.sizeLemmaNextWord(ls, offset + elemSizeOff, otherOffset + elemSizeOtherOff, from + 1, to)
        }
    }.ensuring { (_: Unit) => 
        TTC_3_31_ModifyTheCollectionIntervalOfHousekeepingParameterReportStructures_housekeepingParamererReportStructureIntervals.sizeRange(ls, offset, from, to) == TTC_3_31_ModifyTheCollectionIntervalOfHousekeepingParameterReportStructures_housekeepingParamererReportStructureIntervals.sizeRange(ls, otherOffset, from, to)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextDWord(ls: Vector[THousekeepingParameterReportStructureIntervals], offset: Long, otherOffset: Long, from: Int, to: Int): Unit = {
        require((0 <= from) && (from <= to) && (to <= ls.size) && (ls.size <= 63))
        require((0L <= offset) && (offset <= 9223372036854775807L - 64L * (to - from)))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775807L - 64L * (to - from)))
        require((offset % 32L) == (otherOffset % 32L))
        decreases(to - from)
        if (from == to) {
            ()
        } else {
            val elemSizeOff = ls.apply(from).size(offset)
            val elemSizeOtherOff = ls.apply(from).size(otherOffset)
            assert(elemSizeOff == 64L)
            assert(elemSizeOtherOff == 64L)
            ls.apply(from).sizeLemmaNextDWord(offset, otherOffset)
            TTC_3_31_ModifyTheCollectionIntervalOfHousekeepingParameterReportStructures_housekeepingParamererReportStructureIntervals.sizeLemmaNextDWord(ls, offset + elemSizeOff, otherOffset + elemSizeOtherOff, from + 1, to)
        }
    }.ensuring { (_: Unit) => 
        TTC_3_31_ModifyTheCollectionIntervalOfHousekeepingParameterReportStructures_housekeepingParamererReportStructureIntervals.sizeRange(ls, offset, from, to) == TTC_3_31_ModifyTheCollectionIntervalOfHousekeepingParameterReportStructures_housekeepingParamererReportStructureIntervals.sizeRange(ls, otherOffset, from, to)
    }
}

case class TTC_3_31_ModifyTheCollectionIntervalOfHousekeepingParameterReportStructures (
    housekeepingParamererReportStructureIntervals: TTC_3_31_ModifyTheCollectionIntervalOfHousekeepingParameterReportStructures_housekeepingParamererReportStructureIntervals
) {

    def size(offset: Long): Long = {
        require((0L <= offset) && (offset <= 9223372036854771743L))
        val size_0 = 32L
        val size_1 = this.housekeepingParamererReportStructureIntervals.size(offset + size_0)
        size_0 + size_1
    }.ensuring { (res: Long) => 
        (0L <= res) && (res <= 4064L)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaAnyOffset(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854771743L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854771743L))
        val size_0_offset = 32L
        val size_0_otherOffset = 32L
        val size_1_offset = this.housekeepingParamererReportStructureIntervals.size(offset + size_0_offset)
        val size_1_otherOffset = this.housekeepingParamererReportStructureIntervals.size(otherOffset + size_0_otherOffset)
        this.housekeepingParamererReportStructureIntervals.sizeLemmaAnyOffset(offset + size_0_offset, otherOffset + size_0_otherOffset)
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextByte(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854771743L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854771743L))
        require((offset % 8L) == (otherOffset % 8L))
        val size_0_offset = 32L
        val size_0_otherOffset = 32L
        val size_1_offset = this.housekeepingParamererReportStructureIntervals.size(offset + size_0_offset)
        val size_1_otherOffset = this.housekeepingParamererReportStructureIntervals.size(otherOffset + size_0_otherOffset)
        this.housekeepingParamererReportStructureIntervals.sizeLemmaNextByte(offset + size_0_offset, otherOffset + size_0_otherOffset)
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextWord(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854771743L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854771743L))
        require((offset % 16L) == (otherOffset % 16L))
        val size_0_offset = 32L
        val size_0_otherOffset = 32L
        val size_1_offset = this.housekeepingParamererReportStructureIntervals.size(offset + size_0_offset)
        val size_1_otherOffset = this.housekeepingParamererReportStructureIntervals.size(otherOffset + size_0_otherOffset)
        this.housekeepingParamererReportStructureIntervals.sizeLemmaNextWord(offset + size_0_offset, otherOffset + size_0_otherOffset)
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextDWord(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854771743L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854771743L))
        require((offset % 32L) == (otherOffset % 32L))
        val size_0_offset = 32L
        val size_0_otherOffset = 32L
        val size_1_offset = this.housekeepingParamererReportStructureIntervals.size(offset + size_0_offset)
        val size_1_otherOffset = this.housekeepingParamererReportStructureIntervals.size(otherOffset + size_0_otherOffset)
        this.housekeepingParamererReportStructureIntervals.sizeLemmaNextDWord(offset + size_0_offset, otherOffset + size_0_otherOffset)
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }
}


@inline @cCode.inline val ERR_TC_3_31_MODIFYTHECOLLECTIONINTERVALOFHOUSEKEEPINGPARAMETERREPORTSTRUCTURES_HOUSEKEEPINGPARAMERERREPORTSTRUCTUREINTERVALS: Int = 1006 /*(SIZE(1 .. maxTC-3-31-HousekeepingParamterStructureIntervalCount)) */
@inline @cCode.inline val ERR_TC_3_31_MODIFYTHECOLLECTIONINTERVALOFHOUSEKEEPINGPARAMETERREPORTSTRUCTURES_HOUSEKEEPINGPARAMERERREPORTSTRUCTUREINTERVALS_ELM_2: Int = 1001 /* */

@inline @cCode.inline val ERR_TC_3_31_MODIFYTHECOLLECTIONINTERVALOFHOUSEKEEPINGPARAMETERREPORTSTRUCTURES: Int = 1011 /* */

 
 

@inline @cCode.inline val ERR_ACN_ENCODE_TC_3_31_MODIFYTHECOLLECTIONINTERVALOFHOUSEKEEPINGPARAMETERREPORTSTRUCTURES: Int = 1014 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_3_31_MODIFYTHECOLLECTIONINTERVALOFHOUSEKEEPINGPARAMETERREPORTSTRUCTURES_N_UNINITIALIZED: Int = 1015 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_3_31_MODIFYTHECOLLECTIONINTERVALOFHOUSEKEEPINGPARAMETERREPORTSTRUCTURES_N: Int = 969 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_3_31_MODIFYTHECOLLECTIONINTERVALOFHOUSEKEEPINGPARAMETERREPORTSTRUCTURES_HOUSEKEEPINGPARAMERERREPORTSTRUCTUREINTERVALS: Int = 1009 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_3_31_MODIFYTHECOLLECTIONINTERVALOFHOUSEKEEPINGPARAMETERREPORTSTRUCTURES_HOUSEKEEPINGPARAMERERREPORTSTRUCTUREINTERVALS_ELM_2: Int = 1004 /*  */
@inline @cCode.inline val TTC_3_31_ModifyTheCollectionIntervalOfHousekeepingParameterReportStructures_REQUIRED_BYTES_FOR_ACN_ENCODING = 508
@inline @cCode.inline val TTC_3_31_ModifyTheCollectionIntervalOfHousekeepingParameterReportStructures_REQUIRED_BITS_FOR_ACN_ENCODING = 4064

@inline @cCode.inline val ERR_ACN_DECODE_TC_3_31_MODIFYTHECOLLECTIONINTERVALOFHOUSEKEEPINGPARAMETERREPORTSTRUCTURES: Int = 1016 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_3_31_MODIFYTHECOLLECTIONINTERVALOFHOUSEKEEPINGPARAMETERREPORTSTRUCTURES_N: Int = 970 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_3_31_MODIFYTHECOLLECTIONINTERVALOFHOUSEKEEPINGPARAMETERREPORTSTRUCTURES_HOUSEKEEPINGPARAMERERREPORTSTRUCTUREINTERVALS: Int = 1010 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_3_31_MODIFYTHECOLLECTIONINTERVALOFHOUSEKEEPINGPARAMETERREPORTSTRUCTURES_HOUSEKEEPINGPARAMERERREPORTSTRUCTUREINTERVALS_ELM_2: Int = 1005 /*  */

// @inline @cCode.inline val maxTC_3_31_HousekeepingParamterStructureIntervalCount: Int = 63 // defined in body

