/*
Code automatically generated by asn1scc tool
*/
package asn1src

import asn1scala._
import stainless.lang._
import stainless.annotation._
import stainless.collection._
import stainless.proof._
import StaticChecks._

sealed trait TOBCPExecutionStatus:
    def i: Int
object TOBCPExecutionStatus:
    case object Tinactive extends TOBCPExecutionStatus:
        override def i: Int = 0
    case object TactiveAndRunning extends TOBCPExecutionStatus:
        override def i: Int = 1
    case object TactiveAndHeld extends TOBCPExecutionStatus:
        override def i: Int = 2

// please use the following macros to avoid breaking code.
// type Tinactive = TOBCPExecutionStatus.inactive
// type TactiveAndRunning = TOBCPExecutionStatus.activeAndRunning
// type TactiveAndHeld = TOBCPExecutionStatus.activeAndHeld

@inline @cCode.inline val ERR_OBCPEXECUTIONSTATUS: Int = 47 /*inactive | activeAndRunning | activeAndHeld */

 

@inline @cCode.inline val ERR_ACN_ENCODE_OBCPEXECUTIONSTATUS: Int = 50 /*  */
@inline @cCode.inline val TOBCPExecutionStatus_REQUIRED_BYTES_FOR_ACN_ENCODING = 1
@inline @cCode.inline val TOBCPExecutionStatus_REQUIRED_BITS_FOR_ACN_ENCODING = 2

@inline @cCode.inline val ERR_ACN_DECODE_OBCPEXECUTIONSTATUS: Int = 51 /*  */
sealed trait TOBCPObservabilityLevel:
    def i: Int
object TOBCPObservabilityLevel:
    case object Tno_observability extends TOBCPObservabilityLevel:
        override def i: Int = 0
    case object Tat_procedure_level extends TOBCPObservabilityLevel:
        override def i: Int = 1
    case object Tat_step_level extends TOBCPObservabilityLevel:
        override def i: Int = 2
    case object Tat_detailed_level extends TOBCPObservabilityLevel:
        override def i: Int = 3

// please use the following macros to avoid breaking code.
// type Tno_observability = TOBCPObservabilityLevel.no_observability
// type Tat_procedure_level = TOBCPObservabilityLevel.at_procedure_level
// type Tat_step_level = TOBCPObservabilityLevel.at_step_level
// type Tat_detailed_level = TOBCPObservabilityLevel.at_detailed_level

@inline @cCode.inline val ERR_OBCPOBSERVABILITYLEVEL: Int = 52 /*no-observability | at-procedure-level | at-step-level | at-detailed-level */

 

@inline @cCode.inline val ERR_ACN_ENCODE_OBCPOBSERVABILITYLEVEL: Int = 55 /*  */
@inline @cCode.inline val TOBCPObservabilityLevel_REQUIRED_BYTES_FOR_ACN_ENCODING = 1
@inline @cCode.inline val TOBCPObservabilityLevel_REQUIRED_BITS_FOR_ACN_ENCODING = 2

@inline @cCode.inline val ERR_ACN_DECODE_OBCPOBSERVABILITYLEVEL: Int = 56 /*  */
sealed trait TOBCPStep_ID:
    def i: Int
object TOBCPStep_ID:
    case object TstopAtEndOfCurrentStep extends TOBCPStep_ID:
        override def i: Int = 0
    case object TnextStep extends TOBCPStep_ID:
        override def i: Int = 1

// please use the following macros to avoid breaking code.
// type TstopAtEndOfCurrentStep = TOBCPStep_ID.stopAtEndOfCurrentStep
// type TnextStep = TOBCPStep_ID.nextStep

@inline @cCode.inline val ERR_OBCPSTEP_ID: Int = 57 /*stopAtEndOfCurrentStep | nextStep */

 

@inline @cCode.inline val ERR_ACN_ENCODE_OBCPSTEP_ID: Int = 60 /*  */
@inline @cCode.inline val TOBCPStep_ID_REQUIRED_BYTES_FOR_ACN_ENCODING = 1
@inline @cCode.inline val TOBCPStep_ID_REQUIRED_BITS_FOR_ACN_ENCODING = 2

@inline @cCode.inline val ERR_ACN_DECODE_OBCPSTEP_ID: Int = 61 /*  */


