/*
Code automatically generated by asn1scc tool
*/
package asn1src

import asn1scala._
import stainless.lang._
import stainless.annotation._
import stainless.collection._
import stainless.proof._
import StaticChecks._

type TStorage_ControlConfigurationSizeType = Long


@inline @cCode.inline val ERR_STORAGE_CONTROLCONFIGURATIONSIZETYPE: Int = 2621 /* */

 

@inline @cCode.inline val ERR_ACN_ENCODE_STORAGE_CONTROLCONFIGURATIONSIZETYPE: Int = 2624 /*  */
@inline @cCode.inline val TStorage_ControlConfigurationSizeType_REQUIRED_BYTES_FOR_ACN_ENCODING = 9
@inline @cCode.inline val TStorage_ControlConfigurationSizeType_REQUIRED_BITS_FOR_ACN_ENCODING = 72

@inline @cCode.inline val ERR_ACN_DECODE_STORAGE_CONTROLCONFIGURATIONSIZETYPE: Int = 2625 /*  */

// @inline @cCode.inline val maxConfigurationSize: TStorage_ControlConfigurationSizeType = 31 // defined in body
// @inline @cCode.inline val maxTailSize: TStorage_ControlConfigurationSizeType = 31 // defined in body

