/*
Code automatically generated by asn1scc tool
*/
package asn1src

import asn1scala._
import stainless.lang._
import stainless.annotation._
import stainless.collection._
import stainless.proof._
import StaticChecks._

type TTC_14_14_aDDEventDefinitionIdentifierstOTheEventReportBlockingForwardControlConfiguration = TEventDefinitionForwardControl

object TTC_14_14_aDDEventDefinitionIdentifierstOTheEventReportBlockingForwardControlConfiguration {
    def apply(forwardControl: TEventDefinitionForwardControl_forwardControl): TTC_14_14_aDDEventDefinitionIdentifierstOTheEventReportBlockingForwardControlConfiguration = {
        TEventDefinitionForwardControl(forwardControl)
    }
}



@inline @cCode.inline val ERR_TC_14_14_ADDEVENTDEFINITIONIDENTIFIERSTOTHEEVENTREPORTBLOCKINGFORWARDCONTROLCONFIGURATION_2: Int = 1021 /* */

 

@inline @cCode.inline val ERR_ACN_ENCODE_TC_14_14_ADDEVENTDEFINITIONIDENTIFIERSTOTHEEVENTREPORTBLOCKINGFORWARDCONTROLCONFIGURATION_2: Int = 1024 /*  */
@inline @cCode.inline val TTC_14_14_aDDEventDefinitionIdentifierstOTheEventReportBlockingForwardControlConfiguration_REQUIRED_BYTES_FOR_ACN_ENCODING = 4015
@inline @cCode.inline val TTC_14_14_aDDEventDefinitionIdentifierstOTheEventReportBlockingForwardControlConfiguration_REQUIRED_BITS_FOR_ACN_ENCODING = 32117

@inline @cCode.inline val ERR_ACN_DECODE_TC_14_14_ADDEVENTDEFINITIONIDENTIFIERSTOTHEEVENTREPORTBLOCKINGFORWARDCONTROLCONFIGURATION_2: Int = 1025 /*  */


