/*
Code automatically generated by asn1scc tool
*/
package asn1src

import asn1scala._
import stainless.lang._
import stainless.annotation._
import stainless.collection._
import stainless.proof._
import StaticChecks._

type TEventDefinitionAuxiliaryData = TDummyType


@inline @cCode.inline val ERR_EVENTDEFINITIONAUXILIARYDATA_2: Int = 2125 /* */

 

@inline @cCode.inline val ERR_ACN_ENCODE_EVENTDEFINITIONAUXILIARYDATA_2: Int = 2128 /*  */
@inline @cCode.inline val TEventDefinitionAuxiliaryData_REQUIRED_BYTES_FOR_ACN_ENCODING = 1
@inline @cCode.inline val TEventDefinitionAuxiliaryData_REQUIRED_BITS_FOR_ACN_ENCODING = 4

@inline @cCode.inline val ERR_ACN_DECODE_EVENTDEFINITIONAUXILIARYDATA_2: Int = 2129 /*  */
type TEventDefinition_ID = ULong


@inline @cCode.inline val ERR_EVENTDEFINITION_ID: Int = 2115 /*(0 .. 4294967295) */

 

@inline @cCode.inline val ERR_ACN_ENCODE_EVENTDEFINITION_ID: Int = 2118 /*  */
@inline @cCode.inline val TEventDefinition_ID_REQUIRED_BYTES_FOR_ACN_ENCODING = 4
@inline @cCode.inline val TEventDefinition_ID_REQUIRED_BITS_FOR_ACN_ENCODING = 32

@inline @cCode.inline val ERR_ACN_DECODE_EVENTDEFINITION_ID: Int = 2119 /*  */

// @inline @cCode.inline val eventDefinition_ID_Size: Int = 32 // defined in body

