/*
Code automatically generated by asn1scc tool
*/
package asn1src

import asn1scala._
import stainless.lang.{ghost => ghostExpr, _}
import stainless.annotation._
import stainless.collection._
import stainless.proof._
import StaticChecks._


def TTC_11_15_TimeshiftAllScheduledActivities_IsConstraintValid(pVal: TTC_11_15_TimeshiftAllScheduledActivities): Either[ErrorCode, Int] =
{
    var ret: Either[ErrorCode, Int] = Right(0)
    ret = TCDS_RelativeTime_PFC_2_IsConstraintValid(pVal.timeOffset)
    ret
}

def TTC_11_15_TimeshiftAllScheduledActivities_Initialize(): TTC_11_15_TimeshiftAllScheduledActivities = TTC_11_15_TimeshiftAllScheduledActivities(timeOffset = TCDS_RelativeTime_PFC_2_Initialize())

@opaque @inlineOnce 
def TTC_11_15_TimeshiftAllScheduledActivities_ACN_Encode(pVal: TTC_11_15_TimeshiftAllScheduledActivities, codec: ACN, bCheckConstraints: Boolean): Either[ErrorCode, Int] =  // acn:21
{
    require(codec.base.bitStream.validate_offset_bits(64L))
    TTC_11_15_TimeshiftAllScheduledActivities_IsConstraintValid(pVal) match
        case Left(l) => return Left(l)
        case Right(_) =>
    @ghost val oldCdc = snapshot(codec)
    @ghost val codec_0_1 = snapshot(codec)
    /* Encode timeOffset */
    TCDS_RelativeTime_PFC_2_ACN_Encode(pVal.timeOffset, codec, false) match // uper:6
        case Right(_) =>
        case Left(err) => return Left(err)
    ghostExpr {
        check(codec.base.bitStream.bitIndex <= oldCdc.base.bitStream.bitIndex + 64L)
        check(codec.base.buf.length == oldCdc.base.buf.length)
    }
    @ghost val size_0 = pVal.timeOffset.size(codec_0_1.base.bitStream.bitIndex)
    ghostExpr {
        check(codec.base.bitStream.bitIndex == oldCdc.base.bitStream.bitIndex + size_0)
    }
    ghostExpr {
        check(codec.base.bitStream.bitIndex <= codec_0_1.base.bitStream.bitIndex + 64L)
    }
    ghostExpr {
        check(pVal.size(oldCdc.base.bitStream.bitIndex) == size_0)
    }
    Right(0)
}.ensuring { (res : Either[ErrorCode, Int]) =>
    res match {
        case Left(_) =>
            true
        case Right(_) =>
            old(codec).base.buf.length == codec.base.buf.length && codec.base.bitStream.bitIndex == old(codec).base.bitStream.bitIndex + pVal.size(old(codec).base.bitStream.bitIndex)
    }
}

@opaque @inlineOnce 
def TTC_11_15_TimeshiftAllScheduledActivities_ACN_Decode(codec: ACN): EitherMut[ErrorCode, TTC_11_15_TimeshiftAllScheduledActivities] =
{
    require(codec.base.bitStream.validate_offset_bits(64L))

    @ghost val oldCdc = snapshot(codec)
    @ghost val codec_0_1 = snapshot(codec)
    /* Decode timeOffset */
    val pVal_timeOffset = TCDS_RelativeTime_PFC_2_ACN_Decode(codec) match // uper:13
        case RightMut(decData) => decData
        case LeftMut(err) => return LeftMut(err)
    ghostExpr {
        check(codec.base.bitStream.bitIndex <= oldCdc.base.bitStream.bitIndex + 64L)
        check(codec.base.buf == oldCdc.base.buf)
    }
    @ghost val size_0 = pVal_timeOffset.size(codec_0_1.base.bitStream.bitIndex)
    ghostExpr {
        check(codec.base.bitStream.bitIndex == oldCdc.base.bitStream.bitIndex + size_0)
    }
    ghostExpr {
        check(codec.base.bitStream.bitIndex <= codec_0_1.base.bitStream.bitIndex + 64L)
    }
    val pVal = TTC_11_15_TimeshiftAllScheduledActivities(pVal_timeOffset)
    ghostExpr {
        check(pVal.size(oldCdc.base.bitStream.bitIndex) == size_0)
    }

    TTC_11_15_TimeshiftAllScheduledActivities_IsConstraintValid(pVal) match
        case Left(l) => LeftMut[ErrorCode, TTC_11_15_TimeshiftAllScheduledActivities](l)
        case Right(_) => RightMut[ErrorCode, TTC_11_15_TimeshiftAllScheduledActivities](pVal)
}.ensuring { (res : EitherMut[ErrorCode, TTC_11_15_TimeshiftAllScheduledActivities]) =>
    res match {
        case LeftMut(_) =>
            true
        case RightMut(resVal) =>
            old(codec).base.buf == codec.base.buf && codec.base.bitStream.bitIndex == old(codec).base.bitStream.bitIndex + resVal.size(old(codec).base.bitStream.bitIndex) && TTC_11_15_TimeshiftAllScheduledActivities_IsConstraintValid(resVal).isRight
    }
}

@ghost @pure 
def TTC_11_15_TimeshiftAllScheduledActivities_ACN_Decode_pure(codec: ACN): (ACN, EitherMut[ErrorCode, TTC_11_15_TimeshiftAllScheduledActivities]) =
{
    require(codec.base.bitStream.validate_offset_bits(64L))
    val cpy = snapshot(codec)
    val res = TTC_11_15_TimeshiftAllScheduledActivities_ACN_Decode(cpy)
    (cpy, res)
}