/*
Code automatically generated by asn1scc tool
*/
package asn1src

import asn1scala._
import stainless.lang._
import stainless.annotation._
import stainless.collection._
import stainless.proof._
import StaticChecks._

/*-- TTC_2_2_DistributeRegisterCommands --------------------------------------------*/


case class TTC_2_2_DistributeRegisterCommands_registerCommands (nCount: Int, arr: Vector[TRegister])
{
    require(this.arr.size <= 63 && 1 <= this.nCount && this.nCount <= this.arr.size)

    def size(offset: Long): Long = {
        require((0L <= offset) && (offset <= 9223372036854773287L))
        TTC_2_2_DistributeRegisterCommands_registerCommands.sizeRange(this.arr, offset, 0, this.nCount)
    }.ensuring { (res: Long) => 
        (0L <= res) && (res <= 2520L)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaAnyOffset(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854773287L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854773287L))
        TTC_2_2_DistributeRegisterCommands_registerCommands.sizeLemmaAnyOffset(this.arr, offset, otherOffset, 0, this.nCount)
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextByte(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854773287L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854773287L))
        require((offset % 8L) == (otherOffset % 8L))
        TTC_2_2_DistributeRegisterCommands_registerCommands.sizeLemmaNextByte(this.arr, offset, otherOffset, 0, this.nCount)
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextWord(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854773287L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854773287L))
        require((offset % 16L) == (otherOffset % 16L))
        TTC_2_2_DistributeRegisterCommands_registerCommands.sizeLemmaNextWord(this.arr, offset, otherOffset, 0, this.nCount)
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextDWord(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854773287L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854773287L))
        require((offset % 32L) == (otherOffset % 32L))
        TTC_2_2_DistributeRegisterCommands_registerCommands.sizeLemmaNextDWord(this.arr, offset, otherOffset, 0, this.nCount)
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }
}
object TTC_2_2_DistributeRegisterCommands_registerCommands {
    def sizeRange(ls: Vector[TRegister], offset: Long, from: Int, to: Int): Long = {
        require((0 <= from) && (from <= to) && (to <= ls.size) && (ls.size <= 63))
        require((0L <= offset) && (offset <= 9223372036854775807L - 40L * (to - from)))
        decreases(to - from)
        if (from == to) {
            0L
        } else {
            val elemSize = ls.apply(from).size(offset)
            assert(0L <= elemSize && elemSize <= 40L)
            elemSize + TTC_2_2_DistributeRegisterCommands_registerCommands.sizeRange(ls, offset + elemSize, from + 1, to)
        }
    }.ensuring { (res: Long) => 
        val nbElems = (to - from)
        (0L <= res && res <= 40L * nbElems)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaAnyOffset(ls: Vector[TRegister], offset: Long, otherOffset: Long, from: Int, to: Int): Unit = {
        require((0 <= from) && (from <= to) && (to <= ls.size) && (ls.size <= 63))
        require((0L <= offset) && (offset <= 9223372036854775807L - 40L * (to - from)))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775807L - 40L * (to - from)))
        decreases(to - from)
        if (from == to) {
            ()
        } else {
            val elemSizeOff = ls.apply(from).size(offset)
            val elemSizeOtherOff = ls.apply(from).size(otherOffset)
            assert(0L <= elemSizeOff && elemSizeOff <= 40L)
            assert(0L <= elemSizeOtherOff && elemSizeOtherOff <= 40L)
            ls.apply(from).sizeLemmaAnyOffset(offset, otherOffset)
            TTC_2_2_DistributeRegisterCommands_registerCommands.sizeLemmaAnyOffset(ls, offset + elemSizeOff, otherOffset + elemSizeOtherOff, from + 1, to)
        }
    }.ensuring { (_: Unit) => 
        TTC_2_2_DistributeRegisterCommands_registerCommands.sizeRange(ls, offset, from, to) == TTC_2_2_DistributeRegisterCommands_registerCommands.sizeRange(ls, otherOffset, from, to)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextByte(ls: Vector[TRegister], offset: Long, otherOffset: Long, from: Int, to: Int): Unit = {
        require((0 <= from) && (from <= to) && (to <= ls.size) && (ls.size <= 63))
        require((0L <= offset) && (offset <= 9223372036854775807L - 40L * (to - from)))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775807L - 40L * (to - from)))
        require((offset % 8L) == (otherOffset % 8L))
        decreases(to - from)
        if (from == to) {
            ()
        } else {
            val elemSizeOff = ls.apply(from).size(offset)
            val elemSizeOtherOff = ls.apply(from).size(otherOffset)
            assert(0L <= elemSizeOff && elemSizeOff <= 40L)
            assert(0L <= elemSizeOtherOff && elemSizeOtherOff <= 40L)
            ls.apply(from).sizeLemmaNextByte(offset, otherOffset)
            TTC_2_2_DistributeRegisterCommands_registerCommands.sizeLemmaNextByte(ls, offset + elemSizeOff, otherOffset + elemSizeOtherOff, from + 1, to)
        }
    }.ensuring { (_: Unit) => 
        TTC_2_2_DistributeRegisterCommands_registerCommands.sizeRange(ls, offset, from, to) == TTC_2_2_DistributeRegisterCommands_registerCommands.sizeRange(ls, otherOffset, from, to)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextWord(ls: Vector[TRegister], offset: Long, otherOffset: Long, from: Int, to: Int): Unit = {
        require((0 <= from) && (from <= to) && (to <= ls.size) && (ls.size <= 63))
        require((0L <= offset) && (offset <= 9223372036854775807L - 40L * (to - from)))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775807L - 40L * (to - from)))
        require((offset % 16L) == (otherOffset % 16L))
        decreases(to - from)
        if (from == to) {
            ()
        } else {
            val elemSizeOff = ls.apply(from).size(offset)
            val elemSizeOtherOff = ls.apply(from).size(otherOffset)
            assert(0L <= elemSizeOff && elemSizeOff <= 40L)
            assert(0L <= elemSizeOtherOff && elemSizeOtherOff <= 40L)
            ls.apply(from).sizeLemmaNextWord(offset, otherOffset)
            TTC_2_2_DistributeRegisterCommands_registerCommands.sizeLemmaNextWord(ls, offset + elemSizeOff, otherOffset + elemSizeOtherOff, from + 1, to)
        }
    }.ensuring { (_: Unit) => 
        TTC_2_2_DistributeRegisterCommands_registerCommands.sizeRange(ls, offset, from, to) == TTC_2_2_DistributeRegisterCommands_registerCommands.sizeRange(ls, otherOffset, from, to)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextDWord(ls: Vector[TRegister], offset: Long, otherOffset: Long, from: Int, to: Int): Unit = {
        require((0 <= from) && (from <= to) && (to <= ls.size) && (ls.size <= 63))
        require((0L <= offset) && (offset <= 9223372036854775807L - 40L * (to - from)))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775807L - 40L * (to - from)))
        require((offset % 32L) == (otherOffset % 32L))
        decreases(to - from)
        if (from == to) {
            ()
        } else {
            val elemSizeOff = ls.apply(from).size(offset)
            val elemSizeOtherOff = ls.apply(from).size(otherOffset)
            assert(0L <= elemSizeOff && elemSizeOff <= 40L)
            assert(0L <= elemSizeOtherOff && elemSizeOtherOff <= 40L)
            ls.apply(from).sizeLemmaNextDWord(offset, otherOffset)
            TTC_2_2_DistributeRegisterCommands_registerCommands.sizeLemmaNextDWord(ls, offset + elemSizeOff, otherOffset + elemSizeOtherOff, from + 1, to)
        }
    }.ensuring { (_: Unit) => 
        TTC_2_2_DistributeRegisterCommands_registerCommands.sizeRange(ls, offset, from, to) == TTC_2_2_DistributeRegisterCommands_registerCommands.sizeRange(ls, otherOffset, from, to)
    }
}

case class TTC_2_2_DistributeRegisterCommands (
    registerCommands: TTC_2_2_DistributeRegisterCommands_registerCommands
) {

    def size(offset: Long): Long = {
        require((0L <= offset) && (offset <= 9223372036854773255L))
        val size_0 = 32L
        val size_1 = this.registerCommands.size(offset + size_0)
        size_0 + size_1
    }.ensuring { (res: Long) => 
        (0L <= res) && (res <= 2552L)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaAnyOffset(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854773255L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854773255L))
        val size_0_offset = 32L
        val size_0_otherOffset = 32L
        val size_1_offset = this.registerCommands.size(offset + size_0_offset)
        val size_1_otherOffset = this.registerCommands.size(otherOffset + size_0_otherOffset)
        this.registerCommands.sizeLemmaAnyOffset(offset + size_0_offset, otherOffset + size_0_otherOffset)
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextByte(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854773255L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854773255L))
        require((offset % 8L) == (otherOffset % 8L))
        val size_0_offset = 32L
        val size_0_otherOffset = 32L
        val size_1_offset = this.registerCommands.size(offset + size_0_offset)
        val size_1_otherOffset = this.registerCommands.size(otherOffset + size_0_otherOffset)
        this.registerCommands.sizeLemmaNextByte(offset + size_0_offset, otherOffset + size_0_otherOffset)
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextWord(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854773255L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854773255L))
        require((offset % 16L) == (otherOffset % 16L))
        val size_0_offset = 32L
        val size_0_otherOffset = 32L
        val size_1_offset = this.registerCommands.size(offset + size_0_offset)
        val size_1_otherOffset = this.registerCommands.size(otherOffset + size_0_otherOffset)
        this.registerCommands.sizeLemmaNextWord(offset + size_0_offset, otherOffset + size_0_otherOffset)
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextDWord(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854773255L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854773255L))
        require((offset % 32L) == (otherOffset % 32L))
        val size_0_offset = 32L
        val size_0_otherOffset = 32L
        val size_1_offset = this.registerCommands.size(offset + size_0_offset)
        val size_1_otherOffset = this.registerCommands.size(otherOffset + size_0_otherOffset)
        this.registerCommands.sizeLemmaNextDWord(offset + size_0_offset, otherOffset + size_0_otherOffset)
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }
}


@inline @cCode.inline val ERR_TC_2_2_DISTRIBUTEREGISTERCOMMANDS_REGISTERCOMMANDS: Int = 398 /*(SIZE(1 .. maxTC-2-2-RegisterCommandCount)) */
@inline @cCode.inline val ERR_TC_2_2_DISTRIBUTEREGISTERCOMMANDS_REGISTERCOMMANDS_ELM_2: Int = 393 /* */

@inline @cCode.inline val ERR_TC_2_2_DISTRIBUTEREGISTERCOMMANDS: Int = 403 /* */

 
 

@inline @cCode.inline val ERR_ACN_ENCODE_TC_2_2_DISTRIBUTEREGISTERCOMMANDS: Int = 406 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_2_2_DISTRIBUTEREGISTERCOMMANDS_N_UNINITIALIZED: Int = 407 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_2_2_DISTRIBUTEREGISTERCOMMANDS_N: Int = 366 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_2_2_DISTRIBUTEREGISTERCOMMANDS_REGISTERCOMMANDS: Int = 401 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_2_2_DISTRIBUTEREGISTERCOMMANDS_REGISTERCOMMANDS_ELM_2: Int = 396 /*  */
@inline @cCode.inline val TTC_2_2_DistributeRegisterCommands_REQUIRED_BYTES_FOR_ACN_ENCODING = 319
@inline @cCode.inline val TTC_2_2_DistributeRegisterCommands_REQUIRED_BITS_FOR_ACN_ENCODING = 2552

@inline @cCode.inline val ERR_ACN_DECODE_TC_2_2_DISTRIBUTEREGISTERCOMMANDS: Int = 408 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_2_2_DISTRIBUTEREGISTERCOMMANDS_N: Int = 367 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_2_2_DISTRIBUTEREGISTERCOMMANDS_REGISTERCOMMANDS: Int = 402 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_2_2_DISTRIBUTEREGISTERCOMMANDS_REGISTERCOMMANDS_ELM_2: Int = 397 /*  */

// @inline @cCode.inline val maxTC_2_2_RegisterCommandCount: Int = 63 // defined in body

