/*
Code automatically generated by asn1scc tool
*/
package asn1src

import asn1scala._
import stainless.lang.{ghost => ghostExpr, _}
import stainless.annotation._
import stainless.collection._
import stainless.proof._
import StaticChecks._


def TTC_18_13_LoadAnOBCPByReference_IsConstraintValid(pVal: TTC_18_13_LoadAnOBCPByReference): Either[ErrorCode, Int] =
{
    var ret: Either[ErrorCode, Int] = Right(0)
    ret = TOBCP_ID_IsConstraintValid(pVal.obcp_ID)
    if ret.isRight then
        pVal.filePath match
            case SomeMut(filePath) =>
                ret = TFilePath_IsConstraintValid(filePath)
            case NoneMut() =>
    if ret.isRight then
        ret = (pVal.filePath.isDefined == true) match
            case true =>
                Right(0)
            case false =>
                Left(45)
    ret
}

def TTC_18_13_LoadAnOBCPByReference_Initialize(): TTC_18_13_LoadAnOBCPByReference = TTC_18_13_LoadAnOBCPByReference(obcp_ID = Vector.fill[UByte](5.toInt+1)(0x0.toRawUByte), filePath = SomeMut(TFilePath_Initialize()))

@opaque @inlineOnce 
def TTC_18_13_LoadAnOBCPByReference_ACN_Encode(pVal: TTC_18_13_LoadAnOBCPByReference, codec: ACN, bCheckConstraints: Boolean): Either[ErrorCode, Int] =  // acn:21
{
    require(codec.base.bitStream.validate_offset_bits(57389L))
    TTC_18_13_LoadAnOBCPByReference_IsConstraintValid(pVal) match
        case Left(l) => return Left(l)
        case Right(_) =>
    @ghost val oldCdc = snapshot(codec)
    @ghost val codec_0_1 = snapshot(codec)
    /* Encode obcp_ID */
    TOBCP_ID_ACN_Encode(pVal.obcp_ID, codec, false) match // uper:6
        case Right(_) =>
        case Left(err) => return Left(err)
    ghostExpr {
        BitStream.validateOffsetBitsIneqLemma(codec_0_1.base.bitStream, codec.base.bitStream, 57389L, 35L)
        check(codec.base.bitStream.bitIndex <= oldCdc.base.bitStream.bitIndex + 35L)
        check(codec.base.buf.length == oldCdc.base.buf.length)
    }
    @ghost val size_0 = 35L
    ghostExpr {
        check(codec.base.bitStream.bitIndex == oldCdc.base.bitStream.bitIndex + size_0)
    }
    @ghost val codec_0_2 = snapshot(codec)
    TC_18_13_LoadAnOBCPByReference_filePath_Optional_ACN_Encode(codec, pVal, pVal.filePath) match {
        case Left(l) =>
            return Left(l)
        case Right(_) =>
            ()
    }
    ghostExpr {
        check(codec.base.bitStream.bitIndex <= oldCdc.base.bitStream.bitIndex + 57389L)
        check(codec.base.buf.length == oldCdc.base.buf.length)
    }
    @ghost val size_1 = pVal.filePath match {
        case SomeMut(v) =>
            v.size(codec_0_2.base.bitStream.bitIndex)
        case NoneMut() =>
            0L
    }
    ghostExpr {
        check(codec.base.bitStream.bitIndex == oldCdc.base.bitStream.bitIndex + size_0 + size_1)
    }
    ghostExpr {
        check(codec.base.bitStream.bitIndex <= codec_0_1.base.bitStream.bitIndex + 57389L)
    }
    ghostExpr {
        check(pVal.size(oldCdc.base.bitStream.bitIndex) == size_0 + size_1)
    }
    Right(0)
}.ensuring { (res : Either[ErrorCode, Int]) =>
    res match {
        case Left(_) =>
            true
        case Right(_) =>
            old(codec).base.buf.length == codec.base.buf.length && codec.base.bitStream.bitIndex == old(codec).base.bitStream.bitIndex + pVal.size(old(codec).base.bitStream.bitIndex)
    }
}

@opaque @inlineOnce
def TC_18_13_LoadAnOBCPByReference_filePath_Optional_ACN_Encode(codec: ACN, pVal: TTC_18_13_LoadAnOBCPByReference, filePath: OptionMut[TFilePath]): Either[Int, Int] = {
    require(codec.base.bitStream.validate_offset_bits(57354L))
    @ghost val oldCdc = snapshot(codec)
    /* Encode filePath */
    /* marked as ALWAYS PRESENT, so it must be Some */
    filePath match
        case SomeMut(filePath) =>
            TFilePath_ACN_Encode(filePath, codec, false) match // uper:6
                case Right(_) =>
                case Left(err) => return Left(err)
        case NoneMut() => return Left(628)
    Right[Int, Int](0)
}.ensuring { (res: Either[Int, Int]) => 
    res match {
        case Left(_) =>
            true
        case Right(_) =>
            old(codec).base.buf.length == codec.base.buf.length && codec.base.bitStream.bitIndex == old(codec).base.bitStream.bitIndex + filePath.get.size(old(codec).base.bitStream.bitIndex)
    }
}



@opaque @inlineOnce 
def TTC_18_13_LoadAnOBCPByReference_ACN_Decode(codec: ACN): EitherMut[ErrorCode, TTC_18_13_LoadAnOBCPByReference] =
{
    require(codec.base.bitStream.validate_offset_bits(57389L))

    @ghost val oldCdc = snapshot(codec)
    @ghost val codec_0_1 = snapshot(codec)
    /* Decode obcp_ID */
    val pVal_obcp_ID = TOBCP_ID_ACN_Decode(codec) match // uper:13
        case RightMut(decData) => decData
        case LeftMut(err) => return LeftMut(err)
    ghostExpr {
        BitStream.validateOffsetBitsIneqLemma(codec_0_1.base.bitStream, codec.base.bitStream, 57389L, 35L)
        check(codec.base.bitStream.bitIndex <= oldCdc.base.bitStream.bitIndex + 35L)
        check(codec.base.buf == oldCdc.base.buf)
    }
    @ghost val size_0 = 35L
    ghostExpr {
        check(codec.base.bitStream.bitIndex == oldCdc.base.bitStream.bitIndex + size_0)
    }
    @ghost val codec_0_2 = snapshot(codec)
    val pVal_filePath = TC_18_13_LoadAnOBCPByReference_filePath_Optional_ACN_Decode(codec) match {
        case LeftMut(l) =>
            return LeftMut(l)
        case RightMut(v) =>
            v
    }
    ghostExpr {
        check(codec.base.bitStream.bitIndex <= oldCdc.base.bitStream.bitIndex + 57389L)
        check(codec.base.buf == oldCdc.base.buf)
    }
    @ghost val size_1 = pVal_filePath match {
        case SomeMut(v) =>
            v.size(codec_0_2.base.bitStream.bitIndex)
        case NoneMut() =>
            0L
    }
    ghostExpr {
        check(codec.base.bitStream.bitIndex == oldCdc.base.bitStream.bitIndex + size_0 + size_1)
    }
    ghostExpr {
        check(codec.base.bitStream.bitIndex <= codec_0_1.base.bitStream.bitIndex + 57389L)
    }
    val pVal = TTC_18_13_LoadAnOBCPByReference(pVal_obcp_ID, pVal_filePath)
    ghostExpr {
        check(pVal.size(oldCdc.base.bitStream.bitIndex) == size_0 + size_1)
    }

    TTC_18_13_LoadAnOBCPByReference_IsConstraintValid(pVal) match
        case Left(l) => LeftMut[ErrorCode, TTC_18_13_LoadAnOBCPByReference](l)
        case Right(_) => RightMut[ErrorCode, TTC_18_13_LoadAnOBCPByReference](pVal)
}.ensuring { (res : EitherMut[ErrorCode, TTC_18_13_LoadAnOBCPByReference]) =>
    res match {
        case LeftMut(_) =>
            true
        case RightMut(resVal) =>
            old(codec).base.buf == codec.base.buf && codec.base.bitStream.bitIndex == old(codec).base.bitStream.bitIndex + resVal.size(old(codec).base.bitStream.bitIndex) && TTC_18_13_LoadAnOBCPByReference_IsConstraintValid(resVal).isRight
    }
}

@ghost @pure 
def TTC_18_13_LoadAnOBCPByReference_ACN_Decode_pure(codec: ACN): (ACN, EitherMut[ErrorCode, TTC_18_13_LoadAnOBCPByReference]) =
{
    require(codec.base.bitStream.validate_offset_bits(57389L))
    val cpy = snapshot(codec)
    val res = TTC_18_13_LoadAnOBCPByReference_ACN_Decode(cpy)
    (cpy, res)
}

@opaque @inlineOnce
def TC_18_13_LoadAnOBCPByReference_filePath_Optional_ACN_Decode(codec: ACN): EitherMut[Int, OptionMut[TFilePath]] = {
    require(codec.base.bitStream.validate_offset_bits(57354L))
    @ghost val oldCdc = snapshot(codec)
    /* Decode filePath */
    /* marked as ALWAYS PRESENT */
    val filePath: OptionMut[TFilePath] =
        val pVal_filePath = TFilePath_ACN_Decode(codec) match // uper:13
            case RightMut(decData) => decData
            case LeftMut(err) => return LeftMut(err)
        SomeMut(pVal_filePath)
    RightMut[Int, OptionMut[TFilePath]](filePath)
}.ensuring { (res: EitherMut[Int, OptionMut[TFilePath]]) => 
    res match {
        case LeftMut(_) =>
            true
        case RightMut(resVal) =>
            resVal.isDefined && old(codec).base.buf == codec.base.buf && codec.base.bitStream.bitIndex == old(codec).base.bitStream.bitIndex + resVal.get.size(old(codec).base.bitStream.bitIndex)
    }
}



@ghost @pure
def TC_18_13_LoadAnOBCPByReference_filePath_Optional_ACN_Decode_pure(codec: ACN): (ACN, EitherMut[Int, OptionMut[TFilePath]]) = {
    require(codec.base.bitStream.validate_offset_bits(57354L))
    val cpy = snapshot(codec)
    val res = TC_18_13_LoadAnOBCPByReference_filePath_Optional_ACN_Decode(cpy)
    (cpy, res)
}

