/*
Code automatically generated by asn1scc tool
*/
package asn1src

import asn1scala._
import stainless.lang._
import stainless.annotation._
import stainless.collection._
import stainless.proof._
import StaticChecks._

/*-- TTC_DataNoSecondaryHeader --------------------------------------------*/

case class TTC_DataNoSecondaryHeader (
    data: TTC_NoHeaderPayload, 
    packetErrorControl: OptionMut[TPacketErrorControl]
) {
    require(this.packetErrorControl.isDefined)

    def size(offset: Long): Long = {
        require((0L <= offset) && (offset <= 9223372036854775784L))
        val size_0 = 0L
        val size_1 = this.packetErrorControl match {
            case SomeMut(v) =>
                alignedSizeToByte(16L, offset + size_0)
            case NoneMut() =>
                0L
        }
        size_0 + size_1
    }.ensuring { (res: Long) => 
        (0L <= res) && (res <= 23L)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextByte(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854775784L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775784L))
        require((offset % 8L) == (otherOffset % 8L))
        val size_0_offset = 0L
        val size_0_otherOffset = 0L
        val size_1_offset = this.packetErrorControl match {
            case SomeMut(v) =>
                alignedSizeToByte(16L, offset + size_0_offset)
            case NoneMut() =>
                0L
        }
        val size_1_otherOffset = this.packetErrorControl match {
            case SomeMut(v) =>
                alignedSizeToByte(16L, otherOffset + size_0_otherOffset)
            case NoneMut() =>
                0L
        }
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextWord(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854775784L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775784L))
        require((offset % 16L) == (otherOffset % 16L))
        val size_0_offset = 0L
        val size_0_otherOffset = 0L
        val size_1_offset = this.packetErrorControl match {
            case SomeMut(v) =>
                alignedSizeToByte(16L, offset + size_0_offset)
            case NoneMut() =>
                0L
        }
        val size_1_otherOffset = this.packetErrorControl match {
            case SomeMut(v) =>
                alignedSizeToByte(16L, otherOffset + size_0_otherOffset)
            case NoneMut() =>
                0L
        }
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextDWord(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854775784L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775784L))
        require((offset % 32L) == (otherOffset % 32L))
        val size_0_offset = 0L
        val size_0_otherOffset = 0L
        val size_1_offset = this.packetErrorControl match {
            case SomeMut(v) =>
                alignedSizeToByte(16L, offset + size_0_offset)
            case NoneMut() =>
                0L
        }
        val size_1_otherOffset = this.packetErrorControl match {
            case SomeMut(v) =>
                alignedSizeToByte(16L, otherOffset + size_0_otherOffset)
            case NoneMut() =>
                0L
        }
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }
}


@inline @cCode.inline val ERR_TC_DATANOSECONDARYHEADER: Int = 1953 /*(WITH COMPONENTS {packetErrorControl PRESENT}) */
@inline @cCode.inline val ERR_TC_DATANOSECONDARYHEADER_DATA: Int = 1940 /* */
@inline @cCode.inline val ERR_TC_DATANOSECONDARYHEADER_PACKETERRORCONTROL_2: Int = 1950 /* */

 

@inline @cCode.inline val ERR_ACN_ENCODE_TC_DATANOSECONDARYHEADER: Int = 1956 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_DATANOSECONDARYHEADER_DATA_2: Int = 1943 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_DATANOSECONDARYHEADER_PACKETERRORCONTROL: Int = 1948 /*  */
@inline @cCode.inline val TTC_DataNoSecondaryHeader_REQUIRED_BYTES_FOR_ACN_ENCODING = 3
@inline @cCode.inline val TTC_DataNoSecondaryHeader_REQUIRED_BITS_FOR_ACN_ENCODING = 23

@inline @cCode.inline val ERR_ACN_DECODE_TC_DATANOSECONDARYHEADER: Int = 1957 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_DATANOSECONDARYHEADER_DATA_2: Int = 1944 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_DATANOSECONDARYHEADER_PACKETERRORCONTROL: Int = 1949 /*  */
/*-- TAcknowledgementFlags --------------------------------------------*/

case class TAcknowledgementFlags (
    ackExecutionCompletion: Boolean, 
    ackExecutionProgress: Boolean, 
    ackExecutionStart: Boolean, 
    ackAcceptance: Boolean
) {

    def size(offset: Long): Long = {
        require((0L <= offset) && (offset <= 9223372036854775803L))
        val size_0 = 1L
        val size_1 = 1L
        val size_2 = 1L
        val size_3 = 1L
        size_0 + size_1 + size_2 + size_3
    }.ensuring { (res: Long) => 
        res == 4L
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaAnyOffset(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854775803L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775803L))
        val size_0_offset = 1L
        val size_0_otherOffset = 1L
        val size_1_offset = 1L
        val size_1_otherOffset = 1L
        val size_2_offset = 1L
        val size_2_otherOffset = 1L
        val size_3_offset = 1L
        val size_3_otherOffset = 1L
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextByte(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854775803L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775803L))
        require((offset % 8L) == (otherOffset % 8L))
        val size_0_offset = 1L
        val size_0_otherOffset = 1L
        val size_1_offset = 1L
        val size_1_otherOffset = 1L
        val size_2_offset = 1L
        val size_2_otherOffset = 1L
        val size_3_offset = 1L
        val size_3_otherOffset = 1L
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextWord(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854775803L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775803L))
        require((offset % 16L) == (otherOffset % 16L))
        val size_0_offset = 1L
        val size_0_otherOffset = 1L
        val size_1_offset = 1L
        val size_1_otherOffset = 1L
        val size_2_offset = 1L
        val size_2_otherOffset = 1L
        val size_3_offset = 1L
        val size_3_otherOffset = 1L
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextDWord(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854775803L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775803L))
        require((offset % 32L) == (otherOffset % 32L))
        val size_0_offset = 1L
        val size_0_otherOffset = 1L
        val size_1_offset = 1L
        val size_1_otherOffset = 1L
        val size_2_offset = 1L
        val size_2_otherOffset = 1L
        val size_3_offset = 1L
        val size_3_otherOffset = 1L
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }
}


@inline @cCode.inline val ERR_ACKNOWLEDGEMENTFLAGS: Int = 2135 /* */
@inline @cCode.inline val ERR_ACKNOWLEDGEMENTFLAGS_ACKEXECUTIONCOMPLETION: Int = 2115 /* */
@inline @cCode.inline val ERR_ACKNOWLEDGEMENTFLAGS_ACKEXECUTIONPROGRESS: Int = 2120 /* */
@inline @cCode.inline val ERR_ACKNOWLEDGEMENTFLAGS_ACKEXECUTIONSTART: Int = 2125 /* */
@inline @cCode.inline val ERR_ACKNOWLEDGEMENTFLAGS_ACKACCEPTANCE: Int = 2130 /* */

 

@inline @cCode.inline val ERR_ACN_ENCODE_ACKNOWLEDGEMENTFLAGS: Int = 2138 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_ACKNOWLEDGEMENTFLAGS_ACKEXECUTIONCOMPLETION: Int = 2118 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_ACKNOWLEDGEMENTFLAGS_ACKEXECUTIONPROGRESS: Int = 2123 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_ACKNOWLEDGEMENTFLAGS_ACKEXECUTIONSTART: Int = 2128 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_ACKNOWLEDGEMENTFLAGS_ACKACCEPTANCE: Int = 2133 /*  */
@inline @cCode.inline val TAcknowledgementFlags_REQUIRED_BYTES_FOR_ACN_ENCODING = 1
@inline @cCode.inline val TAcknowledgementFlags_REQUIRED_BITS_FOR_ACN_ENCODING = 4

@inline @cCode.inline val ERR_ACN_DECODE_ACKNOWLEDGEMENTFLAGS: Int = 2139 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_ACKNOWLEDGEMENTFLAGS_ACKEXECUTIONCOMPLETION: Int = 2119 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_ACKNOWLEDGEMENTFLAGS_ACKEXECUTIONPROGRESS: Int = 2124 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_ACKNOWLEDGEMENTFLAGS_ACKEXECUTIONSTART: Int = 2129 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_ACKNOWLEDGEMENTFLAGS_ACKACCEPTANCE: Int = 2134 /*  */
/*-- TTC_PacketSecondaryHeader --------------------------------------------*/

case class TTC_PacketSecondaryHeader (
    tcPacketPusVersionNumber: NullType, 
    acknowledgementFlags: TAcknowledgementFlags, 
    source_ID: TApplicationProcessUser_ID
) {

    def size(offset: Long): Long = {
        require((0L <= offset) && (offset <= 9223372036854775787L))
        val size_0 = 0L
        val size_1 = this.acknowledgementFlags.size(offset + size_0)
        val size_2 = 16L
        size_0 + size_1 + size_2
    }.ensuring { (res: Long) => 
        res == 20L
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaAnyOffset(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854775787L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775787L))
        val size_0_offset = 0L
        val size_0_otherOffset = 0L
        val size_1_offset = this.acknowledgementFlags.size(offset + size_0_offset)
        val size_1_otherOffset = this.acknowledgementFlags.size(otherOffset + size_0_otherOffset)
        this.acknowledgementFlags.sizeLemmaAnyOffset(offset + size_0_offset, otherOffset + size_0_otherOffset)
        val size_2_offset = 16L
        val size_2_otherOffset = 16L
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextByte(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854775787L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775787L))
        require((offset % 8L) == (otherOffset % 8L))
        val size_0_offset = 0L
        val size_0_otherOffset = 0L
        val size_1_offset = this.acknowledgementFlags.size(offset + size_0_offset)
        val size_1_otherOffset = this.acknowledgementFlags.size(otherOffset + size_0_otherOffset)
        this.acknowledgementFlags.sizeLemmaNextByte(offset + size_0_offset, otherOffset + size_0_otherOffset)
        val size_2_offset = 16L
        val size_2_otherOffset = 16L
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextWord(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854775787L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775787L))
        require((offset % 16L) == (otherOffset % 16L))
        val size_0_offset = 0L
        val size_0_otherOffset = 0L
        val size_1_offset = this.acknowledgementFlags.size(offset + size_0_offset)
        val size_1_otherOffset = this.acknowledgementFlags.size(otherOffset + size_0_otherOffset)
        this.acknowledgementFlags.sizeLemmaNextWord(offset + size_0_offset, otherOffset + size_0_otherOffset)
        val size_2_offset = 16L
        val size_2_otherOffset = 16L
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextDWord(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854775787L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775787L))
        require((offset % 32L) == (otherOffset % 32L))
        val size_0_offset = 0L
        val size_0_otherOffset = 0L
        val size_1_offset = this.acknowledgementFlags.size(offset + size_0_offset)
        val size_1_otherOffset = this.acknowledgementFlags.size(otherOffset + size_0_otherOffset)
        this.acknowledgementFlags.sizeLemmaNextDWord(offset + size_0_offset, otherOffset + size_0_otherOffset)
        val size_2_offset = 16L
        val size_2_otherOffset = 16L
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }
}


@inline @cCode.inline val ERR_TC_PACKETSECONDARYHEADER: Int = 2110 /* */
@inline @cCode.inline val ERR_TC_PACKETSECONDARYHEADER_ACKNOWLEDGEMENTFLAGS_2: Int = 2095 /* */
@inline @cCode.inline val ERR_TC_PACKETSECONDARYHEADER_SOURCE_ID_2: Int = 2105 /* */

 

@inline @cCode.inline val ERR_ACN_ENCODE_TC_PACKETSECONDARYHEADER: Int = 2113 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_PACKETSECONDARYHEADER_ACKNOWLEDGEMENTFLAGS_2: Int = 2098 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_PACKETSECONDARYHEADER_SOURCE_ID_2: Int = 2108 /*  */
@inline @cCode.inline val TTC_PacketSecondaryHeader_REQUIRED_BYTES_FOR_ACN_ENCODING = 3
@inline @cCode.inline val TTC_PacketSecondaryHeader_REQUIRED_BITS_FOR_ACN_ENCODING = 20

@inline @cCode.inline val ERR_ACN_DECODE_TC_PACKETSECONDARYHEADER: Int = 2114 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_PACKETSECONDARYHEADER_ACKNOWLEDGEMENTFLAGS_2: Int = 2099 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_PACKETSECONDARYHEADER_SOURCE_ID_2: Int = 2109 /*  */
/*-- TTC_DataWithSecondaryHeader --------------------------------------------*/

case class TTC_DataWithSecondaryHeader (
    secondaryHeader: TTC_PacketSecondaryHeader, 
    data: TTC_Payload, 
    packetErrorControl: OptionMut[TPacketErrorControl]
) {
    require(this.packetErrorControl.isDefined)

    def size(offset: Long): Long = {
        require((0L <= offset) && (offset <= 9223372036854775733L))
        val size_1_0 = 0L
        val size_1_1 = this.secondaryHeader.acknowledgementFlags.size(offset + size_1_0)
        val size_1_2 = 8L
        val size_1_3 = 8L
        val size_1_4 = 16L
        val size_0 = size_1_0 + size_1_1 + size_1_2 + size_1_3 + size_1_4
        val size_1 = this.data match {
            case TTC_Payload.tc_255_255_PRESENT(tc_255_255) =>
                alignedSizeToByte(8L, offset + size_0)
        }
        val size_2 = this.packetErrorControl match {
            case SomeMut(v) =>
                alignedSizeToByte(16L, offset + size_0 + size_1)
            case NoneMut() =>
                0L
        }
        size_0 + size_1 + size_2
    }.ensuring { (res: Long) => 
        (0L <= res) && (res <= 74L)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextByte(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854775733L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775733L))
        require((offset % 8L) == (otherOffset % 8L))
        val size_1_0_offset = 0L
        val size_1_1_offset = this.secondaryHeader.acknowledgementFlags.size(offset + size_1_0_offset)
        val size_1_2_offset = 8L
        val size_1_3_offset = 8L
        val size_1_4_offset = 16L
        val size_0_offset = size_1_0_offset + size_1_1_offset + size_1_2_offset + size_1_3_offset + size_1_4_offset
        val size_1_0_otherOffset = 0L
        val size_1_1_otherOffset = this.secondaryHeader.acknowledgementFlags.size(otherOffset + size_1_0_otherOffset)
        val size_1_2_otherOffset = 8L
        val size_1_3_otherOffset = 8L
        val size_1_4_otherOffset = 16L
        val size_0_otherOffset = size_1_0_otherOffset + size_1_1_otherOffset + size_1_2_otherOffset + size_1_3_otherOffset + size_1_4_otherOffset
        this.secondaryHeader.sizeLemmaNextByte(offset, otherOffset)
        val size_1_offset = this.data match {
            case TTC_Payload.tc_255_255_PRESENT(tc_255_255) =>
                alignedSizeToByte(8L, offset + size_0_offset)
        }
        val size_1_otherOffset = this.data match {
            case TTC_Payload.tc_255_255_PRESENT(tc_255_255) =>
                alignedSizeToByte(8L, otherOffset + size_0_otherOffset)
        }
        this.data.sizeLemmaNextByte(offset + size_0_offset, otherOffset + size_0_otherOffset)
        val size_2_offset = this.packetErrorControl match {
            case SomeMut(v) =>
                alignedSizeToByte(16L, offset + size_0_offset + size_1_offset)
            case NoneMut() =>
                0L
        }
        val size_2_otherOffset = this.packetErrorControl match {
            case SomeMut(v) =>
                alignedSizeToByte(16L, otherOffset + size_0_otherOffset + size_1_otherOffset)
            case NoneMut() =>
                0L
        }
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextWord(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854775733L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775733L))
        require((offset % 16L) == (otherOffset % 16L))
        val size_1_0_offset = 0L
        val size_1_1_offset = this.secondaryHeader.acknowledgementFlags.size(offset + size_1_0_offset)
        val size_1_2_offset = 8L
        val size_1_3_offset = 8L
        val size_1_4_offset = 16L
        val size_0_offset = size_1_0_offset + size_1_1_offset + size_1_2_offset + size_1_3_offset + size_1_4_offset
        val size_1_0_otherOffset = 0L
        val size_1_1_otherOffset = this.secondaryHeader.acknowledgementFlags.size(otherOffset + size_1_0_otherOffset)
        val size_1_2_otherOffset = 8L
        val size_1_3_otherOffset = 8L
        val size_1_4_otherOffset = 16L
        val size_0_otherOffset = size_1_0_otherOffset + size_1_1_otherOffset + size_1_2_otherOffset + size_1_3_otherOffset + size_1_4_otherOffset
        this.secondaryHeader.sizeLemmaNextWord(offset, otherOffset)
        val size_1_offset = this.data match {
            case TTC_Payload.tc_255_255_PRESENT(tc_255_255) =>
                alignedSizeToByte(8L, offset + size_0_offset)
        }
        val size_1_otherOffset = this.data match {
            case TTC_Payload.tc_255_255_PRESENT(tc_255_255) =>
                alignedSizeToByte(8L, otherOffset + size_0_otherOffset)
        }
        this.data.sizeLemmaNextWord(offset + size_0_offset, otherOffset + size_0_otherOffset)
        val size_2_offset = this.packetErrorControl match {
            case SomeMut(v) =>
                alignedSizeToByte(16L, offset + size_0_offset + size_1_offset)
            case NoneMut() =>
                0L
        }
        val size_2_otherOffset = this.packetErrorControl match {
            case SomeMut(v) =>
                alignedSizeToByte(16L, otherOffset + size_0_otherOffset + size_1_otherOffset)
            case NoneMut() =>
                0L
        }
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextDWord(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854775733L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775733L))
        require((offset % 32L) == (otherOffset % 32L))
        val size_1_0_offset = 0L
        val size_1_1_offset = this.secondaryHeader.acknowledgementFlags.size(offset + size_1_0_offset)
        val size_1_2_offset = 8L
        val size_1_3_offset = 8L
        val size_1_4_offset = 16L
        val size_0_offset = size_1_0_offset + size_1_1_offset + size_1_2_offset + size_1_3_offset + size_1_4_offset
        val size_1_0_otherOffset = 0L
        val size_1_1_otherOffset = this.secondaryHeader.acknowledgementFlags.size(otherOffset + size_1_0_otherOffset)
        val size_1_2_otherOffset = 8L
        val size_1_3_otherOffset = 8L
        val size_1_4_otherOffset = 16L
        val size_0_otherOffset = size_1_0_otherOffset + size_1_1_otherOffset + size_1_2_otherOffset + size_1_3_otherOffset + size_1_4_otherOffset
        this.secondaryHeader.sizeLemmaNextDWord(offset, otherOffset)
        val size_1_offset = this.data match {
            case TTC_Payload.tc_255_255_PRESENT(tc_255_255) =>
                alignedSizeToByte(8L, offset + size_0_offset)
        }
        val size_1_otherOffset = this.data match {
            case TTC_Payload.tc_255_255_PRESENT(tc_255_255) =>
                alignedSizeToByte(8L, otherOffset + size_0_otherOffset)
        }
        this.data.sizeLemmaNextDWord(offset + size_0_offset, otherOffset + size_0_otherOffset)
        val size_2_offset = this.packetErrorControl match {
            case SomeMut(v) =>
                alignedSizeToByte(16L, offset + size_0_offset + size_1_offset)
            case NoneMut() =>
                0L
        }
        val size_2_otherOffset = this.packetErrorControl match {
            case SomeMut(v) =>
                alignedSizeToByte(16L, otherOffset + size_0_otherOffset + size_1_otherOffset)
            case NoneMut() =>
                0L
        }
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }
}


@inline @cCode.inline val ERR_TC_DATAWITHSECONDARYHEADER: Int = 2035 /*(WITH COMPONENTS {packetErrorControl PRESENT}) */
@inline @cCode.inline val ERR_TC_DATAWITHSECONDARYHEADER_SECONDARYHEADER_2: Int = 2011 /* */
@inline @cCode.inline val ERR_TC_DATAWITHSECONDARYHEADER_DATA_2: Int = 2024 /* */
@inline @cCode.inline val ERR_TC_DATAWITHSECONDARYHEADER_PACKETERRORCONTROL_2: Int = 2032 /* */

 

@inline @cCode.inline val ERR_ACN_ENCODE_TC_DATAWITHSECONDARYHEADER: Int = 2038 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_DATAWITHSECONDARYHEADER_SECONDARYHEADER: Int = 2009 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_DATAWITHSECONDARYHEADER_SECONDARYHEADER_ACKNOWLEDGEMENTFLAGS_2: Int = 1990 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_DATAWITHSECONDARYHEADER_SECONDARYHEADER_SERVICETYPE_ID_UNINITIALIZED: Int = 2039 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_DATAWITHSECONDARYHEADER_SECONDARYHEADER_SERVICETYPE_ID: Int = 1992 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_DATAWITHSECONDARYHEADER_SECONDARYHEADER_MESSAGESUBTYPE_ID_UNINITIALIZED: Int = 2040 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_DATAWITHSECONDARYHEADER_SECONDARYHEADER_MESSAGESUBTYPE_ID: Int = 1994 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_DATAWITHSECONDARYHEADER_SECONDARYHEADER_SOURCE_ID_2: Int = 2004 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_DATAWITHSECONDARYHEADER_DATA: Int = 2022 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_DATAWITHSECONDARYHEADER_DATA_TC_255_255: Int = 2017 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_DATAWITHSECONDARYHEADER_PACKETERRORCONTROL: Int = 2030 /*  */
@inline @cCode.inline val TTC_DataWithSecondaryHeader_REQUIRED_BYTES_FOR_ACN_ENCODING = 10
@inline @cCode.inline val TTC_DataWithSecondaryHeader_REQUIRED_BITS_FOR_ACN_ENCODING = 74

@inline @cCode.inline val ERR_ACN_DECODE_TC_DATAWITHSECONDARYHEADER: Int = 2041 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_DATAWITHSECONDARYHEADER_SECONDARYHEADER: Int = 2010 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_DATAWITHSECONDARYHEADER_SECONDARYHEADER_ACKNOWLEDGEMENTFLAGS_2: Int = 1991 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_DATAWITHSECONDARYHEADER_SECONDARYHEADER_SERVICETYPE_ID: Int = 1993 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_DATAWITHSECONDARYHEADER_SECONDARYHEADER_MESSAGESUBTYPE_ID: Int = 1995 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_DATAWITHSECONDARYHEADER_SECONDARYHEADER_SOURCE_ID_2: Int = 2005 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_DATAWITHSECONDARYHEADER_DATA: Int = 2023 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_DATAWITHSECONDARYHEADER_DATA_TC_255_255: Int = 2018 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_DATAWITHSECONDARYHEADER_PACKETERRORCONTROL: Int = 2031 /*  */
/*-- TTC_PacketDataField --------------------------------------------*/

enum TTC_PacketDataField:
    case TC_PacketDataField_dataWithSecondaryHeader_PRESENT(dataWithSecondaryHeader: TTC_DataWithSecondaryHeader)
    case TC_PacketDataField_dataNoSecondaryHeader_PRESENT(dataNoSecondaryHeader: TTC_DataNoSecondaryHeader)

    def size(offset: Long): Long = {
        require((0L <= offset) && (offset <= 9223372036854775733L))
        this match {
            case TTC_PacketDataField.TC_PacketDataField_dataWithSecondaryHeader_PRESENT(dataWithSecondaryHeader) =>
                val size_2_0 = 0L
                val size_2_1 = dataWithSecondaryHeader.secondaryHeader.acknowledgementFlags.size(offset + size_2_0)
                val size_2_2 = 8L
                val size_2_3 = 8L
                val size_2_4 = 16L
                val size_1_0 = size_2_0 + size_2_1 + size_2_2 + size_2_3 + size_2_4
                val size_1_1 = dataWithSecondaryHeader.data match {
                    case TTC_Payload.tc_255_255_PRESENT(tc_255_255) =>
                        alignedSizeToByte(8L, offset + size_1_0)
                }
                val size_1_2 = dataWithSecondaryHeader.packetErrorControl match {
                    case SomeMut(v) =>
                        alignedSizeToByte(16L, offset + size_1_0 + size_1_1)
                    case NoneMut() =>
                        0L
                }
                size_1_0 + size_1_1 + size_1_2
            case TTC_PacketDataField.TC_PacketDataField_dataNoSecondaryHeader_PRESENT(dataNoSecondaryHeader) =>
                val size_1_0 = 0L
                val size_1_1 = dataNoSecondaryHeader.packetErrorControl match {
                    case SomeMut(v) =>
                        alignedSizeToByte(16L, offset + size_1_0)
                    case NoneMut() =>
                        0L
                }
                size_1_0 + size_1_1
        }
    }.ensuring { (res: Long) => 
        (0L <= res) && (res <= 74L)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextByte(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854775733L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775733L))
        require((offset % 8L) == (otherOffset % 8L))
        this match {
            case TTC_PacketDataField.TC_PacketDataField_dataWithSecondaryHeader_PRESENT(dataWithSecondaryHeader) =>
                dataWithSecondaryHeader.sizeLemmaNextByte(offset, otherOffset)
            case TTC_PacketDataField.TC_PacketDataField_dataNoSecondaryHeader_PRESENT(dataNoSecondaryHeader) =>
                dataNoSecondaryHeader.sizeLemmaNextByte(offset, otherOffset)
        }
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextWord(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854775733L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775733L))
        require((offset % 16L) == (otherOffset % 16L))
        this match {
            case TTC_PacketDataField.TC_PacketDataField_dataWithSecondaryHeader_PRESENT(dataWithSecondaryHeader) =>
                dataWithSecondaryHeader.sizeLemmaNextWord(offset, otherOffset)
            case TTC_PacketDataField.TC_PacketDataField_dataNoSecondaryHeader_PRESENT(dataNoSecondaryHeader) =>
                dataNoSecondaryHeader.sizeLemmaNextWord(offset, otherOffset)
        }
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextDWord(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854775733L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775733L))
        require((offset % 32L) == (otherOffset % 32L))
        this match {
            case TTC_PacketDataField.TC_PacketDataField_dataWithSecondaryHeader_PRESENT(dataWithSecondaryHeader) =>
                dataWithSecondaryHeader.sizeLemmaNextDWord(offset, otherOffset)
            case TTC_PacketDataField.TC_PacketDataField_dataNoSecondaryHeader_PRESENT(dataNoSecondaryHeader) =>
                dataNoSecondaryHeader.sizeLemmaNextDWord(offset, otherOffset)
        }
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

@inline @cCode.inline val ERR_TC_PACKETDATAFIELD: Int = 1931 /* */
@inline @cCode.inline val ERR_TC_PACKETDATAFIELD_DATAWITHSECONDARYHEADER_2: Int = 1903 /* */
@inline @cCode.inline val ERR_TC_PACKETDATAFIELD_DATANOSECONDARYHEADER_2: Int = 1928 /* */

 
type TTC_PacketType = NullType


 

@inline @cCode.inline val ERR_ACN_ENCODE_TC_PACKETTYPE: Int = 2142 /*  */
@inline @cCode.inline val TTC_PacketType_REQUIRED_BYTES_FOR_ACN_ENCODING = 1
@inline @cCode.inline val TTC_PacketType_REQUIRED_BITS_FOR_ACN_ENCODING = 1

@inline @cCode.inline val ERR_ACN_DECODE_TC_PACKETTYPE: Int = 2143 /*  */
/*-- TTC_Packet_ID --------------------------------------------*/

case class TTC_Packet_ID (
    packetType: TTC_PacketType, 
    applicationProcess_ID: TApplicationProcess_ID
) {

    def size(offset: Long): Long = {
        require((0L <= offset) && (offset <= 9223372036854775795L))
        val size_0 = 1L
        val size_1 = 11L
        size_0 + size_1
    }.ensuring { (res: Long) => 
        res == 12L
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaAnyOffset(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854775795L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775795L))
        val size_0_offset = 1L
        val size_0_otherOffset = 1L
        val size_1_offset = 11L
        val size_1_otherOffset = 11L
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextByte(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854775795L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775795L))
        require((offset % 8L) == (otherOffset % 8L))
        val size_0_offset = 1L
        val size_0_otherOffset = 1L
        val size_1_offset = 11L
        val size_1_otherOffset = 11L
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextWord(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854775795L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775795L))
        require((offset % 16L) == (otherOffset % 16L))
        val size_0_offset = 1L
        val size_0_otherOffset = 1L
        val size_1_offset = 11L
        val size_1_otherOffset = 11L
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextDWord(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854775795L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775795L))
        require((offset % 32L) == (otherOffset % 32L))
        val size_0_offset = 1L
        val size_0_otherOffset = 1L
        val size_1_offset = 11L
        val size_1_otherOffset = 11L
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }
}


@inline @cCode.inline val ERR_TC_PACKET_ID: Int = 2061 /* */
@inline @cCode.inline val ERR_TC_PACKET_ID_PACKETTYPE: Int = 2046 /* */
@inline @cCode.inline val ERR_TC_PACKET_ID_APPLICATIONPROCESS_ID_2: Int = 2056 /* */

 

@inline @cCode.inline val ERR_ACN_ENCODE_TC_PACKET_ID: Int = 2064 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_PACKET_ID_PACKETTYPE_2: Int = 2049 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_PACKET_ID_APPLICATIONPROCESS_ID_2: Int = 2059 /*  */
@inline @cCode.inline val TTC_Packet_ID_REQUIRED_BYTES_FOR_ACN_ENCODING = 2
@inline @cCode.inline val TTC_Packet_ID_REQUIRED_BITS_FOR_ACN_ENCODING = 12

@inline @cCode.inline val ERR_ACN_DECODE_TC_PACKET_ID: Int = 2065 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_PACKET_ID_PACKETTYPE_2: Int = 2050 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_PACKET_ID_APPLICATIONPROCESS_ID_2: Int = 2060 /*  */
/*-- TTC_CCSDS_Packet --------------------------------------------*/

case class TTC_CCSDS_Packet (
    packetVersionNumber: TPacketVersionNumberValue, 
    packet_ID: TTC_Packet_ID, 
    packetSequenceControl: TPacketSequenceControl, 
    packetDataLength: TPacketDataLength, 
    packetDataField: TTC_PacketDataField
) {

    def size(offset: Long): Long = {
        require((0L <= offset) && (offset <= 9223372036854775685L))
        val size_0 = 3L
        val size_1_1 = 1L
        val size_1_2 = 1L
        val size_1_3 = 11L
        val size_1 = size_1_1 + size_1_2 + size_1_3
        val size_2 = this.packetSequenceControl.size(offset + size_0 + size_1)
        val size_3 = 16L
        val size_4 = this.packetDataField match {
            case TTC_PacketDataField.TC_PacketDataField_dataWithSecondaryHeader_PRESENT(dataWithSecondaryHeader) =>
                val size_3_4 = 0L
                val size_3_5 = dataWithSecondaryHeader.secondaryHeader.acknowledgementFlags.size(offset + size_0 + size_1 + size_2 + size_3 + size_3_4)
                val size_3_6 = 8L
                val size_3_7 = 8L
                val size_3_8 = 16L
                val size_2_4 = size_3_4 + size_3_5 + size_3_6 + size_3_7 + size_3_8
                val size_2_5 = dataWithSecondaryHeader.data match {
                    case TTC_Payload.tc_255_255_PRESENT(tc_255_255) =>
                        alignedSizeToByte(8L, offset + size_0 + size_1 + size_2 + size_3 + size_2_4)
                }
                val size_2_6 = dataWithSecondaryHeader.packetErrorControl match {
                    case SomeMut(v) =>
                        alignedSizeToByte(16L, offset + size_0 + size_1 + size_2 + size_3 + size_2_4 + size_2_5)
                    case NoneMut() =>
                        0L
                }
                size_2_4 + size_2_5 + size_2_6
            case TTC_PacketDataField.TC_PacketDataField_dataNoSecondaryHeader_PRESENT(dataNoSecondaryHeader) =>
                val size_2_4 = 0L
                val size_2_5 = dataNoSecondaryHeader.packetErrorControl match {
                    case SomeMut(v) =>
                        alignedSizeToByte(16L, offset + size_0 + size_1 + size_2 + size_3 + size_2_4)
                    case NoneMut() =>
                        0L
                }
                size_2_4 + size_2_5
        }
        size_0 + size_1 + size_2 + size_3 + size_4
    }.ensuring { (res: Long) => 
        (0L <= res) && (res <= 122L)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextByte(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854775685L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775685L))
        require((offset % 8L) == (otherOffset % 8L))
        val size_0_offset = 3L
        val size_0_otherOffset = 3L
        val size_1_1_offset = 1L
        val size_1_2_offset = 1L
        val size_1_3_offset = 11L
        val size_1_offset = size_1_1_offset + size_1_2_offset + size_1_3_offset
        val size_1_1_otherOffset = 1L
        val size_1_2_otherOffset = 1L
        val size_1_3_otherOffset = 11L
        val size_1_otherOffset = size_1_1_otherOffset + size_1_2_otherOffset + size_1_3_otherOffset
        this.packet_ID.sizeLemmaNextByte(offset + size_0_offset, otherOffset + size_0_otherOffset)
        val size_2_offset = this.packetSequenceControl.size(offset + size_0_offset + size_1_offset)
        val size_2_otherOffset = this.packetSequenceControl.size(otherOffset + size_0_otherOffset + size_1_otherOffset)
        this.packetSequenceControl.sizeLemmaNextByte(offset + size_0_offset + size_1_offset, otherOffset + size_0_otherOffset + size_1_otherOffset)
        val size_3_offset = 16L
        val size_3_otherOffset = 16L
        val size_4_offset = this.packetDataField match {
            case TTC_PacketDataField.TC_PacketDataField_dataWithSecondaryHeader_PRESENT(dataWithSecondaryHeader) =>
                val size_3_4 = 0L
                val size_3_5 = dataWithSecondaryHeader.secondaryHeader.acknowledgementFlags.size(offset + size_0_offset + size_1_offset + size_2_offset + size_3_offset + size_3_4)
                val size_3_6 = 8L
                val size_3_7 = 8L
                val size_3_8 = 16L
                val size_2_4 = size_3_4 + size_3_5 + size_3_6 + size_3_7 + size_3_8
                val size_2_5 = dataWithSecondaryHeader.data match {
                    case TTC_Payload.tc_255_255_PRESENT(tc_255_255) =>
                        alignedSizeToByte(8L, offset + size_0_offset + size_1_offset + size_2_offset + size_3_offset + size_2_4)
                }
                val size_2_6 = dataWithSecondaryHeader.packetErrorControl match {
                    case SomeMut(v) =>
                        alignedSizeToByte(16L, offset + size_0_offset + size_1_offset + size_2_offset + size_3_offset + size_2_4 + size_2_5)
                    case NoneMut() =>
                        0L
                }
                size_2_4 + size_2_5 + size_2_6
            case TTC_PacketDataField.TC_PacketDataField_dataNoSecondaryHeader_PRESENT(dataNoSecondaryHeader) =>
                val size_2_4 = 0L
                val size_2_5 = dataNoSecondaryHeader.packetErrorControl match {
                    case SomeMut(v) =>
                        alignedSizeToByte(16L, offset + size_0_offset + size_1_offset + size_2_offset + size_3_offset + size_2_4)
                    case NoneMut() =>
                        0L
                }
                size_2_4 + size_2_5
        }
        val size_4_otherOffset = this.packetDataField match {
            case TTC_PacketDataField.TC_PacketDataField_dataWithSecondaryHeader_PRESENT(dataWithSecondaryHeader) =>
                val size_3_4 = 0L
                val size_3_5 = dataWithSecondaryHeader.secondaryHeader.acknowledgementFlags.size(otherOffset + size_0_otherOffset + size_1_otherOffset + size_2_otherOffset + size_3_otherOffset + size_3_4)
                val size_3_6 = 8L
                val size_3_7 = 8L
                val size_3_8 = 16L
                val size_2_4 = size_3_4 + size_3_5 + size_3_6 + size_3_7 + size_3_8
                val size_2_5 = dataWithSecondaryHeader.data match {
                    case TTC_Payload.tc_255_255_PRESENT(tc_255_255) =>
                        alignedSizeToByte(8L, otherOffset + size_0_otherOffset + size_1_otherOffset + size_2_otherOffset + size_3_otherOffset + size_2_4)
                }
                val size_2_6 = dataWithSecondaryHeader.packetErrorControl match {
                    case SomeMut(v) =>
                        alignedSizeToByte(16L, otherOffset + size_0_otherOffset + size_1_otherOffset + size_2_otherOffset + size_3_otherOffset + size_2_4 + size_2_5)
                    case NoneMut() =>
                        0L
                }
                size_2_4 + size_2_5 + size_2_6
            case TTC_PacketDataField.TC_PacketDataField_dataNoSecondaryHeader_PRESENT(dataNoSecondaryHeader) =>
                val size_2_4 = 0L
                val size_2_5 = dataNoSecondaryHeader.packetErrorControl match {
                    case SomeMut(v) =>
                        alignedSizeToByte(16L, otherOffset + size_0_otherOffset + size_1_otherOffset + size_2_otherOffset + size_3_otherOffset + size_2_4)
                    case NoneMut() =>
                        0L
                }
                size_2_4 + size_2_5
        }
        this.packetDataField.sizeLemmaNextByte(offset + size_0_offset + size_1_offset + size_2_offset + size_3_offset, otherOffset + size_0_otherOffset + size_1_otherOffset + size_2_otherOffset + size_3_otherOffset)
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextWord(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854775685L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775685L))
        require((offset % 16L) == (otherOffset % 16L))
        val size_0_offset = 3L
        val size_0_otherOffset = 3L
        val size_1_1_offset = 1L
        val size_1_2_offset = 1L
        val size_1_3_offset = 11L
        val size_1_offset = size_1_1_offset + size_1_2_offset + size_1_3_offset
        val size_1_1_otherOffset = 1L
        val size_1_2_otherOffset = 1L
        val size_1_3_otherOffset = 11L
        val size_1_otherOffset = size_1_1_otherOffset + size_1_2_otherOffset + size_1_3_otherOffset
        this.packet_ID.sizeLemmaNextWord(offset + size_0_offset, otherOffset + size_0_otherOffset)
        val size_2_offset = this.packetSequenceControl.size(offset + size_0_offset + size_1_offset)
        val size_2_otherOffset = this.packetSequenceControl.size(otherOffset + size_0_otherOffset + size_1_otherOffset)
        this.packetSequenceControl.sizeLemmaNextWord(offset + size_0_offset + size_1_offset, otherOffset + size_0_otherOffset + size_1_otherOffset)
        val size_3_offset = 16L
        val size_3_otherOffset = 16L
        val size_4_offset = this.packetDataField match {
            case TTC_PacketDataField.TC_PacketDataField_dataWithSecondaryHeader_PRESENT(dataWithSecondaryHeader) =>
                val size_3_4 = 0L
                val size_3_5 = dataWithSecondaryHeader.secondaryHeader.acknowledgementFlags.size(offset + size_0_offset + size_1_offset + size_2_offset + size_3_offset + size_3_4)
                val size_3_6 = 8L
                val size_3_7 = 8L
                val size_3_8 = 16L
                val size_2_4 = size_3_4 + size_3_5 + size_3_6 + size_3_7 + size_3_8
                val size_2_5 = dataWithSecondaryHeader.data match {
                    case TTC_Payload.tc_255_255_PRESENT(tc_255_255) =>
                        alignedSizeToByte(8L, offset + size_0_offset + size_1_offset + size_2_offset + size_3_offset + size_2_4)
                }
                val size_2_6 = dataWithSecondaryHeader.packetErrorControl match {
                    case SomeMut(v) =>
                        alignedSizeToByte(16L, offset + size_0_offset + size_1_offset + size_2_offset + size_3_offset + size_2_4 + size_2_5)
                    case NoneMut() =>
                        0L
                }
                size_2_4 + size_2_5 + size_2_6
            case TTC_PacketDataField.TC_PacketDataField_dataNoSecondaryHeader_PRESENT(dataNoSecondaryHeader) =>
                val size_2_4 = 0L
                val size_2_5 = dataNoSecondaryHeader.packetErrorControl match {
                    case SomeMut(v) =>
                        alignedSizeToByte(16L, offset + size_0_offset + size_1_offset + size_2_offset + size_3_offset + size_2_4)
                    case NoneMut() =>
                        0L
                }
                size_2_4 + size_2_5
        }
        val size_4_otherOffset = this.packetDataField match {
            case TTC_PacketDataField.TC_PacketDataField_dataWithSecondaryHeader_PRESENT(dataWithSecondaryHeader) =>
                val size_3_4 = 0L
                val size_3_5 = dataWithSecondaryHeader.secondaryHeader.acknowledgementFlags.size(otherOffset + size_0_otherOffset + size_1_otherOffset + size_2_otherOffset + size_3_otherOffset + size_3_4)
                val size_3_6 = 8L
                val size_3_7 = 8L
                val size_3_8 = 16L
                val size_2_4 = size_3_4 + size_3_5 + size_3_6 + size_3_7 + size_3_8
                val size_2_5 = dataWithSecondaryHeader.data match {
                    case TTC_Payload.tc_255_255_PRESENT(tc_255_255) =>
                        alignedSizeToByte(8L, otherOffset + size_0_otherOffset + size_1_otherOffset + size_2_otherOffset + size_3_otherOffset + size_2_4)
                }
                val size_2_6 = dataWithSecondaryHeader.packetErrorControl match {
                    case SomeMut(v) =>
                        alignedSizeToByte(16L, otherOffset + size_0_otherOffset + size_1_otherOffset + size_2_otherOffset + size_3_otherOffset + size_2_4 + size_2_5)
                    case NoneMut() =>
                        0L
                }
                size_2_4 + size_2_5 + size_2_6
            case TTC_PacketDataField.TC_PacketDataField_dataNoSecondaryHeader_PRESENT(dataNoSecondaryHeader) =>
                val size_2_4 = 0L
                val size_2_5 = dataNoSecondaryHeader.packetErrorControl match {
                    case SomeMut(v) =>
                        alignedSizeToByte(16L, otherOffset + size_0_otherOffset + size_1_otherOffset + size_2_otherOffset + size_3_otherOffset + size_2_4)
                    case NoneMut() =>
                        0L
                }
                size_2_4 + size_2_5
        }
        this.packetDataField.sizeLemmaNextWord(offset + size_0_offset + size_1_offset + size_2_offset + size_3_offset, otherOffset + size_0_otherOffset + size_1_otherOffset + size_2_otherOffset + size_3_otherOffset)
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }

    @ghost @opaque @inlineOnce
    def sizeLemmaNextDWord(offset: Long, otherOffset: Long): Unit = {
        require((0L <= offset) && (offset <= 9223372036854775685L))
        require((0L <= otherOffset) && (otherOffset <= 9223372036854775685L))
        require((offset % 32L) == (otherOffset % 32L))
        val size_0_offset = 3L
        val size_0_otherOffset = 3L
        val size_1_1_offset = 1L
        val size_1_2_offset = 1L
        val size_1_3_offset = 11L
        val size_1_offset = size_1_1_offset + size_1_2_offset + size_1_3_offset
        val size_1_1_otherOffset = 1L
        val size_1_2_otherOffset = 1L
        val size_1_3_otherOffset = 11L
        val size_1_otherOffset = size_1_1_otherOffset + size_1_2_otherOffset + size_1_3_otherOffset
        this.packet_ID.sizeLemmaNextDWord(offset + size_0_offset, otherOffset + size_0_otherOffset)
        val size_2_offset = this.packetSequenceControl.size(offset + size_0_offset + size_1_offset)
        val size_2_otherOffset = this.packetSequenceControl.size(otherOffset + size_0_otherOffset + size_1_otherOffset)
        this.packetSequenceControl.sizeLemmaNextDWord(offset + size_0_offset + size_1_offset, otherOffset + size_0_otherOffset + size_1_otherOffset)
        val size_3_offset = 16L
        val size_3_otherOffset = 16L
        val size_4_offset = this.packetDataField match {
            case TTC_PacketDataField.TC_PacketDataField_dataWithSecondaryHeader_PRESENT(dataWithSecondaryHeader) =>
                val size_3_4 = 0L
                val size_3_5 = dataWithSecondaryHeader.secondaryHeader.acknowledgementFlags.size(offset + size_0_offset + size_1_offset + size_2_offset + size_3_offset + size_3_4)
                val size_3_6 = 8L
                val size_3_7 = 8L
                val size_3_8 = 16L
                val size_2_4 = size_3_4 + size_3_5 + size_3_6 + size_3_7 + size_3_8
                val size_2_5 = dataWithSecondaryHeader.data match {
                    case TTC_Payload.tc_255_255_PRESENT(tc_255_255) =>
                        alignedSizeToByte(8L, offset + size_0_offset + size_1_offset + size_2_offset + size_3_offset + size_2_4)
                }
                val size_2_6 = dataWithSecondaryHeader.packetErrorControl match {
                    case SomeMut(v) =>
                        alignedSizeToByte(16L, offset + size_0_offset + size_1_offset + size_2_offset + size_3_offset + size_2_4 + size_2_5)
                    case NoneMut() =>
                        0L
                }
                size_2_4 + size_2_5 + size_2_6
            case TTC_PacketDataField.TC_PacketDataField_dataNoSecondaryHeader_PRESENT(dataNoSecondaryHeader) =>
                val size_2_4 = 0L
                val size_2_5 = dataNoSecondaryHeader.packetErrorControl match {
                    case SomeMut(v) =>
                        alignedSizeToByte(16L, offset + size_0_offset + size_1_offset + size_2_offset + size_3_offset + size_2_4)
                    case NoneMut() =>
                        0L
                }
                size_2_4 + size_2_5
        }
        val size_4_otherOffset = this.packetDataField match {
            case TTC_PacketDataField.TC_PacketDataField_dataWithSecondaryHeader_PRESENT(dataWithSecondaryHeader) =>
                val size_3_4 = 0L
                val size_3_5 = dataWithSecondaryHeader.secondaryHeader.acknowledgementFlags.size(otherOffset + size_0_otherOffset + size_1_otherOffset + size_2_otherOffset + size_3_otherOffset + size_3_4)
                val size_3_6 = 8L
                val size_3_7 = 8L
                val size_3_8 = 16L
                val size_2_4 = size_3_4 + size_3_5 + size_3_6 + size_3_7 + size_3_8
                val size_2_5 = dataWithSecondaryHeader.data match {
                    case TTC_Payload.tc_255_255_PRESENT(tc_255_255) =>
                        alignedSizeToByte(8L, otherOffset + size_0_otherOffset + size_1_otherOffset + size_2_otherOffset + size_3_otherOffset + size_2_4)
                }
                val size_2_6 = dataWithSecondaryHeader.packetErrorControl match {
                    case SomeMut(v) =>
                        alignedSizeToByte(16L, otherOffset + size_0_otherOffset + size_1_otherOffset + size_2_otherOffset + size_3_otherOffset + size_2_4 + size_2_5)
                    case NoneMut() =>
                        0L
                }
                size_2_4 + size_2_5 + size_2_6
            case TTC_PacketDataField.TC_PacketDataField_dataNoSecondaryHeader_PRESENT(dataNoSecondaryHeader) =>
                val size_2_4 = 0L
                val size_2_5 = dataNoSecondaryHeader.packetErrorControl match {
                    case SomeMut(v) =>
                        alignedSizeToByte(16L, otherOffset + size_0_otherOffset + size_1_otherOffset + size_2_otherOffset + size_3_otherOffset + size_2_4)
                    case NoneMut() =>
                        0L
                }
                size_2_4 + size_2_5
        }
        this.packetDataField.sizeLemmaNextDWord(offset + size_0_offset + size_1_offset + size_2_offset + size_3_offset, otherOffset + size_0_otherOffset + size_1_otherOffset + size_2_otherOffset + size_3_otherOffset)
        ()
    }.ensuring { (res: Unit) => 
        this.size(offset) == this.size(otherOffset)
    }
}


@inline @cCode.inline val ERR_TC_CCSDS_PACKET: Int = 1813 /* */
@inline @cCode.inline val ERR_TC_CCSDS_PACKET_PACKETVERSIONNUMBER: Int = 1632 /* */
@inline @cCode.inline val ERR_TC_CCSDS_PACKET_PACKET_ID_2: Int = 1663 /* */
@inline @cCode.inline val ERR_TC_CCSDS_PACKET_PACKETSEQUENCECONTROL_2: Int = 1680 /* */
@inline @cCode.inline val ERR_TC_CCSDS_PACKET_PACKETDATALENGTH_2: Int = 1690 /* */
@inline @cCode.inline val ERR_TC_CCSDS_PACKET_PACKETDATAFIELD_2: Int = 1810 /* */

 

@inline @cCode.inline val ERR_ACN_ENCODE_TC_CCSDS_PACKET: Int = 1816 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_CCSDS_PACKET_PACKETVERSIONNUMBER_2: Int = 1635 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_CCSDS_PACKET_PACKET_ID: Int = 1661 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_CCSDS_PACKET_PACKET_ID_PACKETTYPE_2: Int = 1644 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_CCSDS_PACKET_PACKET_ID_SECONDARYHEADERFLAG_UNINITIALIZED: Int = 1817 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_CCSDS_PACKET_PACKET_ID_SECONDARYHEADERFLAG: Int = 1646 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_CCSDS_PACKET_PACKET_ID_APPLICATIONPROCESS_ID_2: Int = 1656 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_CCSDS_PACKET_PACKETSEQUENCECONTROL_2: Int = 1683 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_CCSDS_PACKET_PACKETDATALENGTH_2: Int = 1693 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_CCSDS_PACKET_PACKETDATAFIELD: Int = 1808 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_CCSDS_PACKET_PACKETDATAFIELD_DATAWITHSECONDARYHEADER: Int = 1775 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_CCSDS_PACKET_PACKETDATAFIELD_DATAWITHSECONDARYHEADER_SECONDARYHEADER: Int = 1746 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_CCSDS_PACKET_PACKETDATAFIELD_DATAWITHSECONDARYHEADER_SECONDARYHEADER_ACKNOWLEDGEMENTFLAGS_2: Int = 1727 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_CCSDS_PACKET_PACKETDATAFIELD_DATAWITHSECONDARYHEADER_SECONDARYHEADER_SERVICETYPE_ID_UNINITIALIZED: Int = 1818 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_CCSDS_PACKET_PACKETDATAFIELD_DATAWITHSECONDARYHEADER_SECONDARYHEADER_SERVICETYPE_ID: Int = 1729 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_CCSDS_PACKET_PACKETDATAFIELD_DATAWITHSECONDARYHEADER_SECONDARYHEADER_MESSAGESUBTYPE_ID_UNINITIALIZED: Int = 1819 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_CCSDS_PACKET_PACKETDATAFIELD_DATAWITHSECONDARYHEADER_SECONDARYHEADER_MESSAGESUBTYPE_ID: Int = 1731 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_CCSDS_PACKET_PACKETDATAFIELD_DATAWITHSECONDARYHEADER_SECONDARYHEADER_SOURCE_ID_2: Int = 1741 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_CCSDS_PACKET_PACKETDATAFIELD_DATAWITHSECONDARYHEADER_DATA: Int = 1759 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_CCSDS_PACKET_PACKETDATAFIELD_DATAWITHSECONDARYHEADER_DATA_TC_255_255: Int = 1754 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_CCSDS_PACKET_PACKETDATAFIELD_DATAWITHSECONDARYHEADER_PACKETERRORCONTROL: Int = 1767 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_CCSDS_PACKET_PACKETDATAFIELD_DATANOSECONDARYHEADER: Int = 1800 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_CCSDS_PACKET_PACKETDATAFIELD_DATANOSECONDARYHEADER_DATA_2: Int = 1787 /*  */
@inline @cCode.inline val ERR_ACN_ENCODE_TC_CCSDS_PACKET_PACKETDATAFIELD_DATANOSECONDARYHEADER_PACKETERRORCONTROL: Int = 1792 /*  */
@inline @cCode.inline val TTC_CCSDS_Packet_REQUIRED_BYTES_FOR_ACN_ENCODING = 16
@inline @cCode.inline val TTC_CCSDS_Packet_REQUIRED_BITS_FOR_ACN_ENCODING = 122

@inline @cCode.inline val ERR_ACN_DECODE_TC_CCSDS_PACKET: Int = 1820 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_CCSDS_PACKET_PACKETVERSIONNUMBER_2: Int = 1636 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_CCSDS_PACKET_PACKET_ID: Int = 1662 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_CCSDS_PACKET_PACKET_ID_PACKETTYPE_2: Int = 1645 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_CCSDS_PACKET_PACKET_ID_SECONDARYHEADERFLAG: Int = 1647 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_CCSDS_PACKET_PACKET_ID_APPLICATIONPROCESS_ID_2: Int = 1657 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_CCSDS_PACKET_PACKETSEQUENCECONTROL_2: Int = 1684 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_CCSDS_PACKET_PACKETDATALENGTH_2: Int = 1694 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_CCSDS_PACKET_PACKETDATAFIELD: Int = 1809 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_CCSDS_PACKET_PACKETDATAFIELD_DATAWITHSECONDARYHEADER: Int = 1776 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_CCSDS_PACKET_PACKETDATAFIELD_DATAWITHSECONDARYHEADER_SECONDARYHEADER: Int = 1747 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_CCSDS_PACKET_PACKETDATAFIELD_DATAWITHSECONDARYHEADER_SECONDARYHEADER_ACKNOWLEDGEMENTFLAGS_2: Int = 1728 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_CCSDS_PACKET_PACKETDATAFIELD_DATAWITHSECONDARYHEADER_SECONDARYHEADER_SERVICETYPE_ID: Int = 1730 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_CCSDS_PACKET_PACKETDATAFIELD_DATAWITHSECONDARYHEADER_SECONDARYHEADER_MESSAGESUBTYPE_ID: Int = 1732 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_CCSDS_PACKET_PACKETDATAFIELD_DATAWITHSECONDARYHEADER_SECONDARYHEADER_SOURCE_ID_2: Int = 1742 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_CCSDS_PACKET_PACKETDATAFIELD_DATAWITHSECONDARYHEADER_DATA: Int = 1760 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_CCSDS_PACKET_PACKETDATAFIELD_DATAWITHSECONDARYHEADER_DATA_TC_255_255: Int = 1755 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_CCSDS_PACKET_PACKETDATAFIELD_DATAWITHSECONDARYHEADER_PACKETERRORCONTROL: Int = 1768 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_CCSDS_PACKET_PACKETDATAFIELD_DATANOSECONDARYHEADER: Int = 1801 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_CCSDS_PACKET_PACKETDATAFIELD_DATANOSECONDARYHEADER_DATA_2: Int = 1788 /*  */
@inline @cCode.inline val ERR_ACN_DECODE_TC_CCSDS_PACKET_PACKETDATAFIELD_DATANOSECONDARYHEADER_PACKETERRORCONTROL: Int = 1793 /*  */


